// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: notbbg/v1/auth.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClientType int32

const (
	ClientType_CLIENT_TYPE_UNSPECIFIED ClientType = 0
	ClientType_CLIENT_TYPE_TUI         ClientType = 1
	ClientType_CLIENT_TYPE_CLI         ClientType = 2
	ClientType_CLIENT_TYPE_DESKTOP     ClientType = 3
	ClientType_CLIENT_TYPE_PHONE       ClientType = 4
	ClientType_CLIENT_TYPE_AGENT       ClientType = 5
)

// Enum value maps for ClientType.
var (
	ClientType_name = map[int32]string{
		0: "CLIENT_TYPE_UNSPECIFIED",
		1: "CLIENT_TYPE_TUI",
		2: "CLIENT_TYPE_CLI",
		3: "CLIENT_TYPE_DESKTOP",
		4: "CLIENT_TYPE_PHONE",
		5: "CLIENT_TYPE_AGENT",
	}
	ClientType_value = map[string]int32{
		"CLIENT_TYPE_UNSPECIFIED": 0,
		"CLIENT_TYPE_TUI":         1,
		"CLIENT_TYPE_CLI":         2,
		"CLIENT_TYPE_DESKTOP":     3,
		"CLIENT_TYPE_PHONE":       4,
		"CLIENT_TYPE_AGENT":       5,
	}
)

func (x ClientType) Enum() *ClientType {
	p := new(ClientType)
	*p = x
	return p
}

func (x ClientType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ClientType) Descriptor() protoreflect.EnumDescriptor {
	return file_notbbg_v1_auth_proto_enumTypes[0].Descriptor()
}

func (ClientType) Type() protoreflect.EnumType {
	return &file_notbbg_v1_auth_proto_enumTypes[0]
}

func (x ClientType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ClientType.Descriptor instead.
func (ClientType) EnumDescriptor() ([]byte, []int) {
	return file_notbbg_v1_auth_proto_rawDescGZIP(), []int{0}
}

type PairRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OneTimeToken  string                 `protobuf:"bytes,1,opt,name=one_time_token,json=oneTimeToken,proto3" json:"one_time_token,omitempty"`
	ClientName    string                 `protobuf:"bytes,2,opt,name=client_name,json=clientName,proto3" json:"client_name,omitempty"`
	ClientType    ClientType             `protobuf:"varint,3,opt,name=client_type,json=clientType,proto3,enum=notbbg.v1.ClientType" json:"client_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PairRequest) Reset() {
	*x = PairRequest{}
	mi := &file_notbbg_v1_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PairRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PairRequest) ProtoMessage() {}

func (x *PairRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notbbg_v1_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PairRequest.ProtoReflect.Descriptor instead.
func (*PairRequest) Descriptor() ([]byte, []int) {
	return file_notbbg_v1_auth_proto_rawDescGZIP(), []int{0}
}

func (x *PairRequest) GetOneTimeToken() string {
	if x != nil {
		return x.OneTimeToken
	}
	return ""
}

func (x *PairRequest) GetClientName() string {
	if x != nil {
		return x.ClientName
	}
	return ""
}

func (x *PairRequest) GetClientType() ClientType {
	if x != nil {
		return x.ClientType
	}
	return ClientType_CLIENT_TYPE_UNSPECIFIED
}

type PairResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionToken  string                 `protobuf:"bytes,1,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`
	Rights        uint32                 `protobuf:"varint,2,opt,name=rights,proto3" json:"rights,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PairResponse) Reset() {
	*x = PairResponse{}
	mi := &file_notbbg_v1_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PairResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PairResponse) ProtoMessage() {}

func (x *PairResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notbbg_v1_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PairResponse.ProtoReflect.Descriptor instead.
func (*PairResponse) Descriptor() ([]byte, []int) {
	return file_notbbg_v1_auth_proto_rawDescGZIP(), []int{1}
}

func (x *PairResponse) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

func (x *PairResponse) GetRights() uint32 {
	if x != nil {
		return x.Rights
	}
	return 0
}

func (x *PairResponse) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

type AuthenticateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionToken  string                 `protobuf:"bytes,1,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthenticateRequest) Reset() {
	*x = AuthenticateRequest{}
	mi := &file_notbbg_v1_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticateRequest) ProtoMessage() {}

func (x *AuthenticateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notbbg_v1_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticateRequest.ProtoReflect.Descriptor instead.
func (*AuthenticateRequest) Descriptor() ([]byte, []int) {
	return file_notbbg_v1_auth_proto_rawDescGZIP(), []int{2}
}

func (x *AuthenticateRequest) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

type AuthenticateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	SessionToken  string                 `protobuf:"bytes,2,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`
	Rights        uint32                 `protobuf:"varint,3,opt,name=rights,proto3" json:"rights,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthenticateResponse) Reset() {
	*x = AuthenticateResponse{}
	mi := &file_notbbg_v1_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticateResponse) ProtoMessage() {}

func (x *AuthenticateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notbbg_v1_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticateResponse.ProtoReflect.Descriptor instead.
func (*AuthenticateResponse) Descriptor() ([]byte, []int) {
	return file_notbbg_v1_auth_proto_rawDescGZIP(), []int{3}
}

func (x *AuthenticateResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *AuthenticateResponse) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

func (x *AuthenticateResponse) GetRights() uint32 {
	if x != nil {
		return x.Rights
	}
	return 0
}

func (x *AuthenticateResponse) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

type RefreshTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionToken  string                 `protobuf:"bytes,1,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenRequest) Reset() {
	*x = RefreshTokenRequest{}
	mi := &file_notbbg_v1_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenRequest) ProtoMessage() {}

func (x *RefreshTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notbbg_v1_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenRequest.ProtoReflect.Descriptor instead.
func (*RefreshTokenRequest) Descriptor() ([]byte, []int) {
	return file_notbbg_v1_auth_proto_rawDescGZIP(), []int{4}
}

func (x *RefreshTokenRequest) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

type RefreshTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	SessionToken  string                 `protobuf:"bytes,2,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`
	Rights        uint32                 `protobuf:"varint,3,opt,name=rights,proto3" json:"rights,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenResponse) Reset() {
	*x = RefreshTokenResponse{}
	mi := &file_notbbg_v1_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenResponse) ProtoMessage() {}

func (x *RefreshTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notbbg_v1_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenResponse.ProtoReflect.Descriptor instead.
func (*RefreshTokenResponse) Descriptor() ([]byte, []int) {
	return file_notbbg_v1_auth_proto_rawDescGZIP(), []int{5}
}

func (x *RefreshTokenResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *RefreshTokenResponse) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

func (x *RefreshTokenResponse) GetRights() uint32 {
	if x != nil {
		return x.Rights
	}
	return 0
}

func (x *RefreshTokenResponse) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

var File_notbbg_v1_auth_proto protoreflect.FileDescriptor

const file_notbbg_v1_auth_proto_rawDesc = "" +
	"\n" +
	"\x14notbbg/v1/auth.proto\x12\tnotbbg.v1\"\x8c\x01\n" +
	"\vPairRequest\x12$\n" +
	"\x0eone_time_token\x18\x01 \x01(\tR\foneTimeToken\x12\x1f\n" +
	"\vclient_name\x18\x02 \x01(\tR\n" +
	"clientName\x126\n" +
	"\vclient_type\x18\x03 \x01(\x0e2\x15.notbbg.v1.ClientTypeR\n" +
	"clientType\"j\n" +
	"\fPairResponse\x12#\n" +
	"\rsession_token\x18\x01 \x01(\tR\fsessionToken\x12\x16\n" +
	"\x06rights\x18\x02 \x01(\rR\x06rights\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\x03R\texpiresAt\":\n" +
	"\x13AuthenticateRequest\x12#\n" +
	"\rsession_token\x18\x01 \x01(\tR\fsessionToken\"\x88\x01\n" +
	"\x14AuthenticateResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12#\n" +
	"\rsession_token\x18\x02 \x01(\tR\fsessionToken\x12\x16\n" +
	"\x06rights\x18\x03 \x01(\rR\x06rights\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\x03R\texpiresAt\":\n" +
	"\x13RefreshTokenRequest\x12#\n" +
	"\rsession_token\x18\x01 \x01(\tR\fsessionToken\"\x88\x01\n" +
	"\x14RefreshTokenResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12#\n" +
	"\rsession_token\x18\x02 \x01(\tR\fsessionToken\x12\x16\n" +
	"\x06rights\x18\x03 \x01(\rR\x06rights\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\x03R\texpiresAt*\x9a\x01\n" +
	"\n" +
	"ClientType\x12\x1b\n" +
	"\x17CLIENT_TYPE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fCLIENT_TYPE_TUI\x10\x01\x12\x13\n" +
	"\x0fCLIENT_TYPE_CLI\x10\x02\x12\x17\n" +
	"\x13CLIENT_TYPE_DESKTOP\x10\x03\x12\x15\n" +
	"\x11CLIENT_TYPE_PHONE\x10\x04\x12\x15\n" +
	"\x11CLIENT_TYPE_AGENT\x10\x052\xe8\x01\n" +
	"\vAuthService\x127\n" +
	"\x04Pair\x12\x16.notbbg.v1.PairRequest\x1a\x17.notbbg.v1.PairResponse\x12O\n" +
	"\fAuthenticate\x12\x1e.notbbg.v1.AuthenticateRequest\x1a\x1f.notbbg.v1.AuthenticateResponse\x12O\n" +
	"\fRefreshToken\x12\x1e.notbbg.v1.RefreshTokenRequest\x1a\x1f.notbbg.v1.RefreshTokenResponseB.Z,github.com/notbbg/notbbg/server/pkg/protocolb\x06proto3"

var (
	file_notbbg_v1_auth_proto_rawDescOnce sync.Once
	file_notbbg_v1_auth_proto_rawDescData []byte
)

func file_notbbg_v1_auth_proto_rawDescGZIP() []byte {
	file_notbbg_v1_auth_proto_rawDescOnce.Do(func() {
		file_notbbg_v1_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_notbbg_v1_auth_proto_rawDesc), len(file_notbbg_v1_auth_proto_rawDesc)))
	})
	return file_notbbg_v1_auth_proto_rawDescData
}

var file_notbbg_v1_auth_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_notbbg_v1_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_notbbg_v1_auth_proto_goTypes = []any{
	(ClientType)(0),              // 0: notbbg.v1.ClientType
	(*PairRequest)(nil),          // 1: notbbg.v1.PairRequest
	(*PairResponse)(nil),         // 2: notbbg.v1.PairResponse
	(*AuthenticateRequest)(nil),  // 3: notbbg.v1.AuthenticateRequest
	(*AuthenticateResponse)(nil), // 4: notbbg.v1.AuthenticateResponse
	(*RefreshTokenRequest)(nil),  // 5: notbbg.v1.RefreshTokenRequest
	(*RefreshTokenResponse)(nil), // 6: notbbg.v1.RefreshTokenResponse
}
var file_notbbg_v1_auth_proto_depIdxs = []int32{
	0, // 0: notbbg.v1.PairRequest.client_type:type_name -> notbbg.v1.ClientType
	1, // 1: notbbg.v1.AuthService.Pair:input_type -> notbbg.v1.PairRequest
	3, // 2: notbbg.v1.AuthService.Authenticate:input_type -> notbbg.v1.AuthenticateRequest
	5, // 3: notbbg.v1.AuthService.RefreshToken:input_type -> notbbg.v1.RefreshTokenRequest
	2, // 4: notbbg.v1.AuthService.Pair:output_type -> notbbg.v1.PairResponse
	4, // 5: notbbg.v1.AuthService.Authenticate:output_type -> notbbg.v1.AuthenticateResponse
	6, // 6: notbbg.v1.AuthService.RefreshToken:output_type -> notbbg.v1.RefreshTokenResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_notbbg_v1_auth_proto_init() }
func file_notbbg_v1_auth_proto_init() {
	if File_notbbg_v1_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_notbbg_v1_auth_proto_rawDesc), len(file_notbbg_v1_auth_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_notbbg_v1_auth_proto_goTypes,
		DependencyIndexes: file_notbbg_v1_auth_proto_depIdxs,
		EnumInfos:         file_notbbg_v1_auth_proto_enumTypes,
		MessageInfos:      file_notbbg_v1_auth_proto_msgTypes,
	}.Build()
	File_notbbg_v1_auth_proto = out.File
	file_notbbg_v1_auth_proto_goTypes = nil
	file_notbbg_v1_auth_proto_depIdxs = nil
}
