// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: notbbg/v1/feeds.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FeedAction int32

const (
	FeedAction_FEED_ACTION_UNSPECIFIED FeedAction = 0
	FeedAction_FEED_ACTION_START       FeedAction = 1
	FeedAction_FEED_ACTION_STOP        FeedAction = 2
	FeedAction_FEED_ACTION_ADD         FeedAction = 3
	FeedAction_FEED_ACTION_UPDATE      FeedAction = 4
	FeedAction_FEED_ACTION_REMOVE      FeedAction = 5
)

// Enum value maps for FeedAction.
var (
	FeedAction_name = map[int32]string{
		0: "FEED_ACTION_UNSPECIFIED",
		1: "FEED_ACTION_START",
		2: "FEED_ACTION_STOP",
		3: "FEED_ACTION_ADD",
		4: "FEED_ACTION_UPDATE",
		5: "FEED_ACTION_REMOVE",
	}
	FeedAction_value = map[string]int32{
		"FEED_ACTION_UNSPECIFIED": 0,
		"FEED_ACTION_START":       1,
		"FEED_ACTION_STOP":        2,
		"FEED_ACTION_ADD":         3,
		"FEED_ACTION_UPDATE":      4,
		"FEED_ACTION_REMOVE":      5,
	}
)

func (x FeedAction) Enum() *FeedAction {
	p := new(FeedAction)
	*p = x
	return p
}

func (x FeedAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FeedAction) Descriptor() protoreflect.EnumDescriptor {
	return file_notbbg_v1_feeds_proto_enumTypes[0].Descriptor()
}

func (FeedAction) Type() protoreflect.EnumType {
	return &file_notbbg_v1_feeds_proto_enumTypes[0]
}

func (x FeedAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FeedAction.Descriptor instead.
func (FeedAction) EnumDescriptor() ([]byte, []int) {
	return file_notbbg_v1_feeds_proto_rawDescGZIP(), []int{0}
}

// Configuration for a data feed source.
type FeedConfig struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Name                string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // unique feed identifier
	Type                string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"` // "ccxt", "rest", "rss", "websocket"
	Enabled             bool                   `protobuf:"varint,3,opt,name=enabled,proto3" json:"enabled,omitempty"`
	PollIntervalSeconds int32                  `protobuf:"varint,4,opt,name=poll_interval_seconds,json=pollIntervalSeconds,proto3" json:"poll_interval_seconds,omitempty"`                   // for polling feeds
	Params              map[string]string      `protobuf:"bytes,5,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // feed-specific config (exchange, symbols, urls, etc.)
	CacheTtlSeconds     int32                  `protobuf:"varint,6,opt,name=cache_ttl_seconds,json=cacheTtlSeconds,proto3" json:"cache_ttl_seconds,omitempty"`                               // how long to cache results
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *FeedConfig) Reset() {
	*x = FeedConfig{}
	mi := &file_notbbg_v1_feeds_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeedConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedConfig) ProtoMessage() {}

func (x *FeedConfig) ProtoReflect() protoreflect.Message {
	mi := &file_notbbg_v1_feeds_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedConfig.ProtoReflect.Descriptor instead.
func (*FeedConfig) Descriptor() ([]byte, []int) {
	return file_notbbg_v1_feeds_proto_rawDescGZIP(), []int{0}
}

func (x *FeedConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FeedConfig) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *FeedConfig) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *FeedConfig) GetPollIntervalSeconds() int32 {
	if x != nil {
		return x.PollIntervalSeconds
	}
	return 0
}

func (x *FeedConfig) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *FeedConfig) GetCacheTtlSeconds() int32 {
	if x != nil {
		return x.CacheTtlSeconds
	}
	return 0
}

// Request to manage feeds at runtime.
type FeedControlRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FeedName      string                 `protobuf:"bytes,1,opt,name=feed_name,json=feedName,proto3" json:"feed_name,omitempty"`
	Action        FeedAction             `protobuf:"varint,2,opt,name=action,proto3,enum=notbbg.v1.FeedAction" json:"action,omitempty"`
	Config        *FeedConfig            `protobuf:"bytes,3,opt,name=config,proto3" json:"config,omitempty"` // for ADD/UPDATE actions
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeedControlRequest) Reset() {
	*x = FeedControlRequest{}
	mi := &file_notbbg_v1_feeds_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeedControlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedControlRequest) ProtoMessage() {}

func (x *FeedControlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notbbg_v1_feeds_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedControlRequest.ProtoReflect.Descriptor instead.
func (*FeedControlRequest) Descriptor() ([]byte, []int) {
	return file_notbbg_v1_feeds_proto_rawDescGZIP(), []int{1}
}

func (x *FeedControlRequest) GetFeedName() string {
	if x != nil {
		return x.FeedName
	}
	return ""
}

func (x *FeedControlRequest) GetAction() FeedAction {
	if x != nil {
		return x.Action
	}
	return FeedAction_FEED_ACTION_UNSPECIFIED
}

func (x *FeedControlRequest) GetConfig() *FeedConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type FeedControlResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeedControlResponse) Reset() {
	*x = FeedControlResponse{}
	mi := &file_notbbg_v1_feeds_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeedControlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedControlResponse) ProtoMessage() {}

func (x *FeedControlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notbbg_v1_feeds_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedControlResponse.ProtoReflect.Descriptor instead.
func (*FeedControlResponse) Descriptor() ([]byte, []int) {
	return file_notbbg_v1_feeds_proto_rawDescGZIP(), []int{2}
}

func (x *FeedControlResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *FeedControlResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_notbbg_v1_feeds_proto protoreflect.FileDescriptor

const file_notbbg_v1_feeds_proto_rawDesc = "" +
	"\n" +
	"\x15notbbg/v1/feeds.proto\x12\tnotbbg.v1\"\xa4\x02\n" +
	"\n" +
	"FeedConfig\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x18\n" +
	"\aenabled\x18\x03 \x01(\bR\aenabled\x122\n" +
	"\x15poll_interval_seconds\x18\x04 \x01(\x05R\x13pollIntervalSeconds\x129\n" +
	"\x06params\x18\x05 \x03(\v2!.notbbg.v1.FeedConfig.ParamsEntryR\x06params\x12*\n" +
	"\x11cache_ttl_seconds\x18\x06 \x01(\x05R\x0fcacheTtlSeconds\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8f\x01\n" +
	"\x12FeedControlRequest\x12\x1b\n" +
	"\tfeed_name\x18\x01 \x01(\tR\bfeedName\x12-\n" +
	"\x06action\x18\x02 \x01(\x0e2\x15.notbbg.v1.FeedActionR\x06action\x12-\n" +
	"\x06config\x18\x03 \x01(\v2\x15.notbbg.v1.FeedConfigR\x06config\"I\n" +
	"\x13FeedControlResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage*\x9b\x01\n" +
	"\n" +
	"FeedAction\x12\x1b\n" +
	"\x17FEED_ACTION_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11FEED_ACTION_START\x10\x01\x12\x14\n" +
	"\x10FEED_ACTION_STOP\x10\x02\x12\x13\n" +
	"\x0fFEED_ACTION_ADD\x10\x03\x12\x16\n" +
	"\x12FEED_ACTION_UPDATE\x10\x04\x12\x16\n" +
	"\x12FEED_ACTION_REMOVE\x10\x05B.Z,github.com/notbbg/notbbg/server/pkg/protocolb\x06proto3"

var (
	file_notbbg_v1_feeds_proto_rawDescOnce sync.Once
	file_notbbg_v1_feeds_proto_rawDescData []byte
)

func file_notbbg_v1_feeds_proto_rawDescGZIP() []byte {
	file_notbbg_v1_feeds_proto_rawDescOnce.Do(func() {
		file_notbbg_v1_feeds_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_notbbg_v1_feeds_proto_rawDesc), len(file_notbbg_v1_feeds_proto_rawDesc)))
	})
	return file_notbbg_v1_feeds_proto_rawDescData
}

var file_notbbg_v1_feeds_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_notbbg_v1_feeds_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_notbbg_v1_feeds_proto_goTypes = []any{
	(FeedAction)(0),             // 0: notbbg.v1.FeedAction
	(*FeedConfig)(nil),          // 1: notbbg.v1.FeedConfig
	(*FeedControlRequest)(nil),  // 2: notbbg.v1.FeedControlRequest
	(*FeedControlResponse)(nil), // 3: notbbg.v1.FeedControlResponse
	nil,                         // 4: notbbg.v1.FeedConfig.ParamsEntry
}
var file_notbbg_v1_feeds_proto_depIdxs = []int32{
	4, // 0: notbbg.v1.FeedConfig.params:type_name -> notbbg.v1.FeedConfig.ParamsEntry
	0, // 1: notbbg.v1.FeedControlRequest.action:type_name -> notbbg.v1.FeedAction
	1, // 2: notbbg.v1.FeedControlRequest.config:type_name -> notbbg.v1.FeedConfig
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_notbbg_v1_feeds_proto_init() }
func file_notbbg_v1_feeds_proto_init() {
	if File_notbbg_v1_feeds_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_notbbg_v1_feeds_proto_rawDesc), len(file_notbbg_v1_feeds_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_notbbg_v1_feeds_proto_goTypes,
		DependencyIndexes: file_notbbg_v1_feeds_proto_depIdxs,
		EnumInfos:         file_notbbg_v1_feeds_proto_enumTypes,
		MessageInfos:      file_notbbg_v1_feeds_proto_msgTypes,
	}.Build()
	File_notbbg_v1_feeds_proto = out.File
	file_notbbg_v1_feeds_proto_goTypes = nil
	file_notbbg_v1_feeds_proto_depIdxs = nil
}
