// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: notbbg/v1/plugin.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JobState int32

const (
	JobState_JOB_STATE_UNSPECIFIED JobState = 0
	JobState_JOB_STATE_PENDING     JobState = 1
	JobState_JOB_STATE_RUNNING     JobState = 2
	JobState_JOB_STATE_COMPLETED   JobState = 3
	JobState_JOB_STATE_FAILED      JobState = 4
	JobState_JOB_STATE_CANCELLED   JobState = 5
)

// Enum value maps for JobState.
var (
	JobState_name = map[int32]string{
		0: "JOB_STATE_UNSPECIFIED",
		1: "JOB_STATE_PENDING",
		2: "JOB_STATE_RUNNING",
		3: "JOB_STATE_COMPLETED",
		4: "JOB_STATE_FAILED",
		5: "JOB_STATE_CANCELLED",
	}
	JobState_value = map[string]int32{
		"JOB_STATE_UNSPECIFIED": 0,
		"JOB_STATE_PENDING":     1,
		"JOB_STATE_RUNNING":     2,
		"JOB_STATE_COMPLETED":   3,
		"JOB_STATE_FAILED":      4,
		"JOB_STATE_CANCELLED":   5,
	}
)

func (x JobState) Enum() *JobState {
	p := new(JobState)
	*p = x
	return p
}

func (x JobState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JobState) Descriptor() protoreflect.EnumDescriptor {
	return file_notbbg_v1_plugin_proto_enumTypes[0].Descriptor()
}

func (JobState) Type() protoreflect.EnumType {
	return &file_notbbg_v1_plugin_proto_enumTypes[0]
}

func (x JobState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JobState.Descriptor instead.
func (JobState) EnumDescriptor() ([]byte, []int) {
	return file_notbbg_v1_plugin_proto_rawDescGZIP(), []int{0}
}

// CellStyle controls text appearance.
type CellStyle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fg            string                 `protobuf:"bytes,1,opt,name=fg,proto3" json:"fg,omitempty"` // foreground color: "green", "red", "#FF4444", etc.
	Bg            string                 `protobuf:"bytes,2,opt,name=bg,proto3" json:"bg,omitempty"` // background color
	Bold          bool                   `protobuf:"varint,3,opt,name=bold,proto3" json:"bold,omitempty"`
	Italic        bool                   `protobuf:"varint,4,opt,name=italic,proto3" json:"italic,omitempty"`
	Underline     bool                   `protobuf:"varint,5,opt,name=underline,proto3" json:"underline,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CellStyle) Reset() {
	*x = CellStyle{}
	mi := &file_notbbg_v1_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CellStyle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CellStyle) ProtoMessage() {}

func (x *CellStyle) ProtoReflect() protoreflect.Message {
	mi := &file_notbbg_v1_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CellStyle.ProtoReflect.Descriptor instead.
func (*CellStyle) Descriptor() ([]byte, []int) {
	return file_notbbg_v1_plugin_proto_rawDescGZIP(), []int{0}
}

func (x *CellStyle) GetFg() string {
	if x != nil {
		return x.Fg
	}
	return ""
}

func (x *CellStyle) GetBg() string {
	if x != nil {
		return x.Bg
	}
	return ""
}

func (x *CellStyle) GetBold() bool {
	if x != nil {
		return x.Bold
	}
	return false
}

func (x *CellStyle) GetItalic() bool {
	if x != nil {
		return x.Italic
	}
	return false
}

func (x *CellStyle) GetUnderline() bool {
	if x != nil {
		return x.Underline
	}
	return false
}

// CellAddress identifies a cell within a screen.
type CellAddress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Row           uint32                 `protobuf:"varint,1,opt,name=row,proto3" json:"row,omitempty"`
	Col           uint32                 `protobuf:"varint,2,opt,name=col,proto3" json:"col,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CellAddress) Reset() {
	*x = CellAddress{}
	mi := &file_notbbg_v1_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CellAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CellAddress) ProtoMessage() {}

func (x *CellAddress) ProtoReflect() protoreflect.Message {
	mi := &file_notbbg_v1_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CellAddress.ProtoReflect.Descriptor instead.
func (*CellAddress) Descriptor() ([]byte, []int) {
	return file_notbbg_v1_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *CellAddress) GetRow() uint32 {
	if x != nil {
		return x.Row
	}
	return 0
}

func (x *CellAddress) GetCol() uint32 {
	if x != nil {
		return x.Col
	}
	return 0
}

// EnumOption is a single value in an enum dropdown.
type EnumOption struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"` // internal value sent back to plugin
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"` // display label
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnumOption) Reset() {
	*x = EnumOption{}
	mi := &file_notbbg_v1_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnumOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnumOption) ProtoMessage() {}

func (x *EnumOption) ProtoReflect() protoreflect.Message {
	mi := &file_notbbg_v1_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnumOption.ProtoReflect.Descriptor instead.
func (*EnumOption) Descriptor() ([]byte, []int) {
	return file_notbbg_v1_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *EnumOption) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *EnumOption) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

// InputConfig defines an interactive input cell.
type InputConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Input:
	//
	//	*InputConfig_Decimal
	//	*InputConfig_Integer
	//	*InputConfig_StringInput
	//	*InputConfig_EnumInput
	//	*InputConfig_Selection
	Input         isInputConfig_Input `protobuf_oneof:"input"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InputConfig) Reset() {
	*x = InputConfig{}
	mi := &file_notbbg_v1_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InputConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputConfig) ProtoMessage() {}

func (x *InputConfig) ProtoReflect() protoreflect.Message {
	mi := &file_notbbg_v1_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputConfig.ProtoReflect.Descriptor instead.
func (*InputConfig) Descriptor() ([]byte, []int) {
	return file_notbbg_v1_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *InputConfig) GetInput() isInputConfig_Input {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *InputConfig) GetDecimal() *DecimalInput {
	if x != nil {
		if x, ok := x.Input.(*InputConfig_Decimal); ok {
			return x.Decimal
		}
	}
	return nil
}

func (x *InputConfig) GetInteger() *IntegerInput {
	if x != nil {
		if x, ok := x.Input.(*InputConfig_Integer); ok {
			return x.Integer
		}
	}
	return nil
}

func (x *InputConfig) GetStringInput() *StringInput {
	if x != nil {
		if x, ok := x.Input.(*InputConfig_StringInput); ok {
			return x.StringInput
		}
	}
	return nil
}

func (x *InputConfig) GetEnumInput() *EnumInput {
	if x != nil {
		if x, ok := x.Input.(*InputConfig_EnumInput); ok {
			return x.EnumInput
		}
	}
	return nil
}

func (x *InputConfig) GetSelection() *SelectionInput {
	if x != nil {
		if x, ok := x.Input.(*InputConfig_Selection); ok {
			return x.Selection
		}
	}
	return nil
}

type isInputConfig_Input interface {
	isInputConfig_Input()
}

type InputConfig_Decimal struct {
	Decimal *DecimalInput `protobuf:"bytes,1,opt,name=decimal,proto3,oneof"`
}

type InputConfig_Integer struct {
	Integer *IntegerInput `protobuf:"bytes,2,opt,name=integer,proto3,oneof"`
}

type InputConfig_StringInput struct {
	StringInput *StringInput `protobuf:"bytes,3,opt,name=string_input,json=stringInput,proto3,oneof"`
}

type InputConfig_EnumInput struct {
	EnumInput *EnumInput `protobuf:"bytes,4,opt,name=enum_input,json=enumInput,proto3,oneof"`
}

type InputConfig_Selection struct {
	Selection *SelectionInput `protobuf:"bytes,5,opt,name=selection,proto3,oneof"`
}

func (*InputConfig_Decimal) isInputConfig_Input() {}

func (*InputConfig_Integer) isInputConfig_Input() {}

func (*InputConfig_StringInput) isInputConfig_Input() {}

func (*InputConfig_EnumInput) isInputConfig_Input() {}

func (*InputConfig_Selection) isInputConfig_Input() {}

type DecimalInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         float64                `protobuf:"fixed64,1,opt,name=value,proto3" json:"value,omitempty"`
	Min           float64                `protobuf:"fixed64,2,opt,name=min,proto3" json:"min,omitempty"`
	Max           float64                `protobuf:"fixed64,3,opt,name=max,proto3" json:"max,omitempty"`
	Precision     uint32                 `protobuf:"varint,4,opt,name=precision,proto3" json:"precision,omitempty"` // decimal places (default 2)
	Label         string                 `protobuf:"bytes,5,opt,name=label,proto3" json:"label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecimalInput) Reset() {
	*x = DecimalInput{}
	mi := &file_notbbg_v1_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecimalInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecimalInput) ProtoMessage() {}

func (x *DecimalInput) ProtoReflect() protoreflect.Message {
	mi := &file_notbbg_v1_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecimalInput.ProtoReflect.Descriptor instead.
func (*DecimalInput) Descriptor() ([]byte, []int) {
	return file_notbbg_v1_plugin_proto_rawDescGZIP(), []int{4}
}

func (x *DecimalInput) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *DecimalInput) GetMin() float64 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *DecimalInput) GetMax() float64 {
	if x != nil {
		return x.Max
	}
	return 0
}

func (x *DecimalInput) GetPrecision() uint32 {
	if x != nil {
		return x.Precision
	}
	return 0
}

func (x *DecimalInput) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

type IntegerInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         int64                  `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	Min           int64                  `protobuf:"varint,2,opt,name=min,proto3" json:"min,omitempty"`
	Max           int64                  `protobuf:"varint,3,opt,name=max,proto3" json:"max,omitempty"`
	Step          int64                  `protobuf:"varint,4,opt,name=step,proto3" json:"step,omitempty"` // default 1
	Label         string                 `protobuf:"bytes,5,opt,name=label,proto3" json:"label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IntegerInput) Reset() {
	*x = IntegerInput{}
	mi := &file_notbbg_v1_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntegerInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntegerInput) ProtoMessage() {}

func (x *IntegerInput) ProtoReflect() protoreflect.Message {
	mi := &file_notbbg_v1_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntegerInput.ProtoReflect.Descriptor instead.
func (*IntegerInput) Descriptor() ([]byte, []int) {
	return file_notbbg_v1_plugin_proto_rawDescGZIP(), []int{5}
}

func (x *IntegerInput) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *IntegerInput) GetMin() int64 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *IntegerInput) GetMax() int64 {
	if x != nil {
		return x.Max
	}
	return 0
}

func (x *IntegerInput) GetStep() int64 {
	if x != nil {
		return x.Step
	}
	return 0
}

func (x *IntegerInput) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

type StringInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Placeholder   string                 `protobuf:"bytes,2,opt,name=placeholder,proto3" json:"placeholder,omitempty"`
	Label         string                 `protobuf:"bytes,3,opt,name=label,proto3" json:"label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringInput) Reset() {
	*x = StringInput{}
	mi := &file_notbbg_v1_plugin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringInput) ProtoMessage() {}

func (x *StringInput) ProtoReflect() protoreflect.Message {
	mi := &file_notbbg_v1_plugin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringInput.ProtoReflect.Descriptor instead.
func (*StringInput) Descriptor() ([]byte, []int) {
	return file_notbbg_v1_plugin_proto_rawDescGZIP(), []int{6}
}

func (x *StringInput) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *StringInput) GetPlaceholder() string {
	if x != nil {
		return x.Placeholder
	}
	return ""
}

func (x *StringInput) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

type EnumInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"` // current selected value
	Options       []*EnumOption          `protobuf:"bytes,2,rep,name=options,proto3" json:"options,omitempty"`
	Label         string                 `protobuf:"bytes,3,opt,name=label,proto3" json:"label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnumInput) Reset() {
	*x = EnumInput{}
	mi := &file_notbbg_v1_plugin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnumInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnumInput) ProtoMessage() {}

func (x *EnumInput) ProtoReflect() protoreflect.Message {
	mi := &file_notbbg_v1_plugin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnumInput.ProtoReflect.Descriptor instead.
func (*EnumInput) Descriptor() ([]byte, []int) {
	return file_notbbg_v1_plugin_proto_rawDescGZIP(), []int{7}
}

func (x *EnumInput) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *EnumInput) GetOptions() []*EnumOption {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *EnumInput) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

type SelectionInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"` // current selected ticker/pair
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	SearchHint    string                 `protobuf:"bytes,3,opt,name=search_hint,json=searchHint,proto3" json:"search_hint,omitempty"` // e.g. "Search instruments..."
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SelectionInput) Reset() {
	*x = SelectionInput{}
	mi := &file_notbbg_v1_plugin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SelectionInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectionInput) ProtoMessage() {}

func (x *SelectionInput) ProtoReflect() protoreflect.Message {
	mi := &file_notbbg_v1_plugin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectionInput.ProtoReflect.Descriptor instead.
func (*SelectionInput) Descriptor() ([]byte, []int) {
	return file_notbbg_v1_plugin_proto_rawDescGZIP(), []int{8}
}

func (x *SelectionInput) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *SelectionInput) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *SelectionInput) GetSearchHint() string {
	if x != nil {
		return x.SearchHint
	}
	return ""
}

// NumberOutput displays a formatted numeric result.
type NumberOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         float64                `protobuf:"fixed64,1,opt,name=value,proto3" json:"value,omitempty"`
	Precision     uint32                 `protobuf:"varint,2,opt,name=precision,proto3" json:"precision,omitempty"` // decimal places
	Unit          string                 `protobuf:"bytes,3,opt,name=unit,proto3" json:"unit,omitempty"`            // optional suffix: "%", "ms", "$", etc.
	Delta         string                 `protobuf:"bytes,4,opt,name=delta,proto3" json:"delta,omitempty"`          // "up", "down", "" — controls ▲▼ indicator
	Label         string                 `protobuf:"bytes,5,opt,name=label,proto3" json:"label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NumberOutput) Reset() {
	*x = NumberOutput{}
	mi := &file_notbbg_v1_plugin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NumberOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NumberOutput) ProtoMessage() {}

func (x *NumberOutput) ProtoReflect() protoreflect.Message {
	mi := &file_notbbg_v1_plugin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NumberOutput.ProtoReflect.Descriptor instead.
func (*NumberOutput) Descriptor() ([]byte, []int) {
	return file_notbbg_v1_plugin_proto_rawDescGZIP(), []int{9}
}

func (x *NumberOutput) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *NumberOutput) GetPrecision() uint32 {
	if x != nil {
		return x.Precision
	}
	return 0
}

func (x *NumberOutput) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *NumberOutput) GetDelta() string {
	if x != nil {
		return x.Delta
	}
	return ""
}

func (x *NumberOutput) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

// FormulaCell holds an Excel-style formula.
type FormulaCell struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Expression    string                 `protobuf:"bytes,1,opt,name=expression,proto3" json:"expression,omitempty"`                        // e.g. "=BS(R1C1, R2C1, R2C3, ...)"
	CachedValue   float64                `protobuf:"fixed64,2,opt,name=cached_value,json=cachedValue,proto3" json:"cached_value,omitempty"` // last computed value (for display before recalc)
	Precision     uint32                 `protobuf:"varint,3,opt,name=precision,proto3" json:"precision,omitempty"`                         // decimal places for display
	Label         string                 `protobuf:"bytes,4,opt,name=label,proto3" json:"label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FormulaCell) Reset() {
	*x = FormulaCell{}
	mi := &file_notbbg_v1_plugin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FormulaCell) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FormulaCell) ProtoMessage() {}

func (x *FormulaCell) ProtoReflect() protoreflect.Message {
	mi := &file_notbbg_v1_plugin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FormulaCell.ProtoReflect.Descriptor instead.
func (*FormulaCell) Descriptor() ([]byte, []int) {
	return file_notbbg_v1_plugin_proto_rawDescGZIP(), []int{10}
}

func (x *FormulaCell) GetExpression() string {
	if x != nil {
		return x.Expression
	}
	return ""
}

func (x *FormulaCell) GetCachedValue() float64 {
	if x != nil {
		return x.CachedValue
	}
	return 0
}

func (x *FormulaCell) GetPrecision() uint32 {
	if x != nil {
		return x.Precision
	}
	return 0
}

func (x *FormulaCell) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

// Cell is the fundamental unit of the grid.
type Cell struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Address *CellAddress           `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Style   *CellStyle             `protobuf:"bytes,2,opt,name=style,proto3" json:"style,omitempty"`
	// Types that are valid to be assigned to Content:
	//
	//	*Cell_Text
	//	*Cell_Input
	//	*Cell_Number
	//	*Cell_Formula
	//	*Cell_Component
	Content isCell_Content `protobuf_oneof:"content"`
	// Conditional visibility: cell hidden unless condition met.
	// Empty string = always visible. Format: "R0C3=Barrier" (show if row0,col3 equals "Barrier").
	VisibleWhen string `protobuf:"bytes,20,opt,name=visible_when,json=visibleWhen,proto3" json:"visible_when,omitempty"`
	// Span: how many columns/rows this cell occupies (default 1).
	ColSpan       uint32 `protobuf:"varint,21,opt,name=col_span,json=colSpan,proto3" json:"col_span,omitempty"`
	RowSpan       uint32 `protobuf:"varint,22,opt,name=row_span,json=rowSpan,proto3" json:"row_span,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cell) Reset() {
	*x = Cell{}
	mi := &file_notbbg_v1_plugin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cell) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cell) ProtoMessage() {}

func (x *Cell) ProtoReflect() protoreflect.Message {
	mi := &file_notbbg_v1_plugin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cell.ProtoReflect.Descriptor instead.
func (*Cell) Descriptor() ([]byte, []int) {
	return file_notbbg_v1_plugin_proto_rawDescGZIP(), []int{11}
}

func (x *Cell) GetAddress() *CellAddress {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *Cell) GetStyle() *CellStyle {
	if x != nil {
		return x.Style
	}
	return nil
}

func (x *Cell) GetContent() isCell_Content {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *Cell) GetText() string {
	if x != nil {
		if x, ok := x.Content.(*Cell_Text); ok {
			return x.Text
		}
	}
	return ""
}

func (x *Cell) GetInput() *InputConfig {
	if x != nil {
		if x, ok := x.Content.(*Cell_Input); ok {
			return x.Input
		}
	}
	return nil
}

func (x *Cell) GetNumber() *NumberOutput {
	if x != nil {
		if x, ok := x.Content.(*Cell_Number); ok {
			return x.Number
		}
	}
	return nil
}

func (x *Cell) GetFormula() *FormulaCell {
	if x != nil {
		if x, ok := x.Content.(*Cell_Formula); ok {
			return x.Formula
		}
	}
	return nil
}

func (x *Cell) GetComponent() string {
	if x != nil {
		if x, ok := x.Content.(*Cell_Component); ok {
			return x.Component
		}
	}
	return ""
}

func (x *Cell) GetVisibleWhen() string {
	if x != nil {
		return x.VisibleWhen
	}
	return ""
}

func (x *Cell) GetColSpan() uint32 {
	if x != nil {
		return x.ColSpan
	}
	return 0
}

func (x *Cell) GetRowSpan() uint32 {
	if x != nil {
		return x.RowSpan
	}
	return 0
}

type isCell_Content interface {
	isCell_Content()
}

type Cell_Text struct {
	Text string `protobuf:"bytes,10,opt,name=text,proto3,oneof"` // styled text (headers, labels)
}

type Cell_Input struct {
	Input *InputConfig `protobuf:"bytes,11,opt,name=input,proto3,oneof"` // interactive input
}

type Cell_Number struct {
	Number *NumberOutput `protobuf:"bytes,12,opt,name=number,proto3,oneof"` // formatted numeric output
}

type Cell_Formula struct {
	Formula *FormulaCell `protobuf:"bytes,13,opt,name=formula,proto3,oneof"` // Excel-style formula
}

type Cell_Component struct {
	Component string `protobuf:"bytes,14,opt,name=component,proto3,oneof"` // component ID: "chart", "progress", "sparkline", etc.
}

func (*Cell_Text) isCell_Content() {}

func (*Cell_Input) isCell_Content() {}

func (*Cell_Number) isCell_Content() {}

func (*Cell_Formula) isCell_Content() {}

func (*Cell_Component) isCell_Content() {}

// Screen is a grid of cells, possibly divided into sub-screens.
type Screen struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Cells         []*Cell                `protobuf:"bytes,3,rep,name=cells,proto3" json:"cells,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Screen) Reset() {
	*x = Screen{}
	mi := &file_notbbg_v1_plugin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Screen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Screen) ProtoMessage() {}

func (x *Screen) ProtoReflect() protoreflect.Message {
	mi := &file_notbbg_v1_plugin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Screen.ProtoReflect.Descriptor instead.
func (*Screen) Descriptor() ([]byte, []int) {
	return file_notbbg_v1_plugin_proto_rawDescGZIP(), []int{12}
}

func (x *Screen) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Screen) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *Screen) GetCells() []*Cell {
	if x != nil {
		return x.Cells
	}
	return nil
}

// ScreenUpdate sends incremental cell changes (not the full grid).
type ScreenUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScreenId      string                 `protobuf:"bytes,1,opt,name=screen_id,json=screenId,proto3" json:"screen_id,omitempty"`
	Cells         []*Cell                `protobuf:"bytes,2,rep,name=cells,proto3" json:"cells,omitempty"`                                 // only cells that changed
	FullReplace   bool                   `protobuf:"varint,3,opt,name=full_replace,json=fullReplace,proto3" json:"full_replace,omitempty"` // if true, replace entire grid (initial load)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScreenUpdate) Reset() {
	*x = ScreenUpdate{}
	mi := &file_notbbg_v1_plugin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScreenUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScreenUpdate) ProtoMessage() {}

func (x *ScreenUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_notbbg_v1_plugin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScreenUpdate.ProtoReflect.Descriptor instead.
func (*ScreenUpdate) Descriptor() ([]byte, []int) {
	return file_notbbg_v1_plugin_proto_rawDescGZIP(), []int{13}
}

func (x *ScreenUpdate) GetScreenId() string {
	if x != nil {
		return x.ScreenId
	}
	return ""
}

func (x *ScreenUpdate) GetCells() []*Cell {
	if x != nil {
		return x.Cells
	}
	return nil
}

func (x *ScreenUpdate) GetFullReplace() bool {
	if x != nil {
		return x.FullReplace
	}
	return false
}

// PluginRegister announces a plugin's capabilities to the server.
type PluginRegister struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PluginName      string                 `protobuf:"bytes,1,opt,name=plugin_name,json=pluginName,proto3" json:"plugin_name,omitempty"`
	Screens         []*Screen              `protobuf:"bytes,2,rep,name=screens,proto3" json:"screens,omitempty"`                                        // initial screen layouts
	SubscribeTopics []string               `protobuf:"bytes,3,rep,name=subscribe_topics,json=subscribeTopics,proto3" json:"subscribe_topics,omitempty"` // data the plugin wants to receive
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PluginRegister) Reset() {
	*x = PluginRegister{}
	mi := &file_notbbg_v1_plugin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginRegister) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginRegister) ProtoMessage() {}

func (x *PluginRegister) ProtoReflect() protoreflect.Message {
	mi := &file_notbbg_v1_plugin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginRegister.ProtoReflect.Descriptor instead.
func (*PluginRegister) Descriptor() ([]byte, []int) {
	return file_notbbg_v1_plugin_proto_rawDescGZIP(), []int{14}
}

func (x *PluginRegister) GetPluginName() string {
	if x != nil {
		return x.PluginName
	}
	return ""
}

func (x *PluginRegister) GetScreens() []*Screen {
	if x != nil {
		return x.Screens
	}
	return nil
}

func (x *PluginRegister) GetSubscribeTopics() []string {
	if x != nil {
		return x.SubscribeTopics
	}
	return nil
}

// PluginDataPush delivers subscribed data from the server to a plugin.
type PluginDataPush struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"` // serialized market data
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginDataPush) Reset() {
	*x = PluginDataPush{}
	mi := &file_notbbg_v1_plugin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginDataPush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginDataPush) ProtoMessage() {}

func (x *PluginDataPush) ProtoReflect() protoreflect.Message {
	mi := &file_notbbg_v1_plugin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginDataPush.ProtoReflect.Descriptor instead.
func (*PluginDataPush) Descriptor() ([]byte, []int) {
	return file_notbbg_v1_plugin_proto_rawDescGZIP(), []int{15}
}

func (x *PluginDataPush) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *PluginDataPush) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *PluginDataPush) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// PluginInputEvent is sent from the GUI to the plugin when a user edits an input cell.
type PluginInputEvent struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	ScreenId string                 `protobuf:"bytes,1,opt,name=screen_id,json=screenId,proto3" json:"screen_id,omitempty"`
	Address  *CellAddress           `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	// Types that are valid to be assigned to Value:
	//
	//	*PluginInputEvent_DecimalValue
	//	*PluginInputEvent_IntegerValue
	//	*PluginInputEvent_StringValue
	//	*PluginInputEvent_EnumValue
	//	*PluginInputEvent_SelectionValue
	Value         isPluginInputEvent_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginInputEvent) Reset() {
	*x = PluginInputEvent{}
	mi := &file_notbbg_v1_plugin_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginInputEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginInputEvent) ProtoMessage() {}

func (x *PluginInputEvent) ProtoReflect() protoreflect.Message {
	mi := &file_notbbg_v1_plugin_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginInputEvent.ProtoReflect.Descriptor instead.
func (*PluginInputEvent) Descriptor() ([]byte, []int) {
	return file_notbbg_v1_plugin_proto_rawDescGZIP(), []int{16}
}

func (x *PluginInputEvent) GetScreenId() string {
	if x != nil {
		return x.ScreenId
	}
	return ""
}

func (x *PluginInputEvent) GetAddress() *CellAddress {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *PluginInputEvent) GetValue() isPluginInputEvent_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *PluginInputEvent) GetDecimalValue() float64 {
	if x != nil {
		if x, ok := x.Value.(*PluginInputEvent_DecimalValue); ok {
			return x.DecimalValue
		}
	}
	return 0
}

func (x *PluginInputEvent) GetIntegerValue() int64 {
	if x != nil {
		if x, ok := x.Value.(*PluginInputEvent_IntegerValue); ok {
			return x.IntegerValue
		}
	}
	return 0
}

func (x *PluginInputEvent) GetStringValue() string {
	if x != nil {
		if x, ok := x.Value.(*PluginInputEvent_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *PluginInputEvent) GetEnumValue() string {
	if x != nil {
		if x, ok := x.Value.(*PluginInputEvent_EnumValue); ok {
			return x.EnumValue
		}
	}
	return ""
}

func (x *PluginInputEvent) GetSelectionValue() string {
	if x != nil {
		if x, ok := x.Value.(*PluginInputEvent_SelectionValue); ok {
			return x.SelectionValue
		}
	}
	return ""
}

type isPluginInputEvent_Value interface {
	isPluginInputEvent_Value()
}

type PluginInputEvent_DecimalValue struct {
	DecimalValue float64 `protobuf:"fixed64,10,opt,name=decimal_value,json=decimalValue,proto3,oneof"`
}

type PluginInputEvent_IntegerValue struct {
	IntegerValue int64 `protobuf:"varint,11,opt,name=integer_value,json=integerValue,proto3,oneof"`
}

type PluginInputEvent_StringValue struct {
	StringValue string `protobuf:"bytes,12,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type PluginInputEvent_EnumValue struct {
	EnumValue string `protobuf:"bytes,13,opt,name=enum_value,json=enumValue,proto3,oneof"` // selected enum option value
}

type PluginInputEvent_SelectionValue struct {
	SelectionValue string `protobuf:"bytes,14,opt,name=selection_value,json=selectionValue,proto3,oneof"` // selected ticker/pair
}

func (*PluginInputEvent_DecimalValue) isPluginInputEvent_Value() {}

func (*PluginInputEvent_IntegerValue) isPluginInputEvent_Value() {}

func (*PluginInputEvent_StringValue) isPluginInputEvent_Value() {}

func (*PluginInputEvent_EnumValue) isPluginInputEvent_Value() {}

func (*PluginInputEvent_SelectionValue) isPluginInputEvent_Value() {}

// PluginJobStatus reports async job progress.
type PluginJobStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	ScreenId      string                 `protobuf:"bytes,2,opt,name=screen_id,json=screenId,proto3" json:"screen_id,omitempty"`
	State         JobState               `protobuf:"varint,3,opt,name=state,proto3,enum=notbbg.v1.JobState" json:"state,omitempty"`
	Progress      float32                `protobuf:"fixed32,4,opt,name=progress,proto3" json:"progress,omitempty"` // 0.0 to 1.0
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`     // status text: "Compiling...", "Running 42/100", etc.
	Error         string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`         // non-empty on failure
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginJobStatus) Reset() {
	*x = PluginJobStatus{}
	mi := &file_notbbg_v1_plugin_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginJobStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginJobStatus) ProtoMessage() {}

func (x *PluginJobStatus) ProtoReflect() protoreflect.Message {
	mi := &file_notbbg_v1_plugin_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginJobStatus.ProtoReflect.Descriptor instead.
func (*PluginJobStatus) Descriptor() ([]byte, []int) {
	return file_notbbg_v1_plugin_proto_rawDescGZIP(), []int{17}
}

func (x *PluginJobStatus) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *PluginJobStatus) GetScreenId() string {
	if x != nil {
		return x.ScreenId
	}
	return ""
}

func (x *PluginJobStatus) GetState() JobState {
	if x != nil {
		return x.State
	}
	return JobState_JOB_STATE_UNSPECIFIED
}

func (x *PluginJobStatus) GetProgress() float32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *PluginJobStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PluginJobStatus) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// PluginMessage wraps all plugin ↔ server communication.
type PluginMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*PluginMessage_Register
	//	*PluginMessage_Screen
	//	*PluginMessage_Data
	//	*PluginMessage_InputEvent
	//	*PluginMessage_JobStatus
	Message       isPluginMessage_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginMessage) Reset() {
	*x = PluginMessage{}
	mi := &file_notbbg_v1_plugin_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginMessage) ProtoMessage() {}

func (x *PluginMessage) ProtoReflect() protoreflect.Message {
	mi := &file_notbbg_v1_plugin_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginMessage.ProtoReflect.Descriptor instead.
func (*PluginMessage) Descriptor() ([]byte, []int) {
	return file_notbbg_v1_plugin_proto_rawDescGZIP(), []int{18}
}

func (x *PluginMessage) GetMessage() isPluginMessage_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *PluginMessage) GetRegister() *PluginRegister {
	if x != nil {
		if x, ok := x.Message.(*PluginMessage_Register); ok {
			return x.Register
		}
	}
	return nil
}

func (x *PluginMessage) GetScreen() *ScreenUpdate {
	if x != nil {
		if x, ok := x.Message.(*PluginMessage_Screen); ok {
			return x.Screen
		}
	}
	return nil
}

func (x *PluginMessage) GetData() *PluginDataPush {
	if x != nil {
		if x, ok := x.Message.(*PluginMessage_Data); ok {
			return x.Data
		}
	}
	return nil
}

func (x *PluginMessage) GetInputEvent() *PluginInputEvent {
	if x != nil {
		if x, ok := x.Message.(*PluginMessage_InputEvent); ok {
			return x.InputEvent
		}
	}
	return nil
}

func (x *PluginMessage) GetJobStatus() *PluginJobStatus {
	if x != nil {
		if x, ok := x.Message.(*PluginMessage_JobStatus); ok {
			return x.JobStatus
		}
	}
	return nil
}

type isPluginMessage_Message interface {
	isPluginMessage_Message()
}

type PluginMessage_Register struct {
	Register *PluginRegister `protobuf:"bytes,1,opt,name=register,proto3,oneof"`
}

type PluginMessage_Screen struct {
	Screen *ScreenUpdate `protobuf:"bytes,2,opt,name=screen,proto3,oneof"`
}

type PluginMessage_Data struct {
	Data *PluginDataPush `protobuf:"bytes,3,opt,name=data,proto3,oneof"`
}

type PluginMessage_InputEvent struct {
	InputEvent *PluginInputEvent `protobuf:"bytes,4,opt,name=input_event,json=inputEvent,proto3,oneof"`
}

type PluginMessage_JobStatus struct {
	JobStatus *PluginJobStatus `protobuf:"bytes,5,opt,name=job_status,json=jobStatus,proto3,oneof"`
}

func (*PluginMessage_Register) isPluginMessage_Message() {}

func (*PluginMessage_Screen) isPluginMessage_Message() {}

func (*PluginMessage_Data) isPluginMessage_Message() {}

func (*PluginMessage_InputEvent) isPluginMessage_Message() {}

func (*PluginMessage_JobStatus) isPluginMessage_Message() {}

var File_notbbg_v1_plugin_proto protoreflect.FileDescriptor

const file_notbbg_v1_plugin_proto_rawDesc = "" +
	"\n" +
	"\x16notbbg/v1/plugin.proto\x12\tnotbbg.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"u\n" +
	"\tCellStyle\x12\x0e\n" +
	"\x02fg\x18\x01 \x01(\tR\x02fg\x12\x0e\n" +
	"\x02bg\x18\x02 \x01(\tR\x02bg\x12\x12\n" +
	"\x04bold\x18\x03 \x01(\bR\x04bold\x12\x16\n" +
	"\x06italic\x18\x04 \x01(\bR\x06italic\x12\x1c\n" +
	"\tunderline\x18\x05 \x01(\bR\tunderline\"1\n" +
	"\vCellAddress\x12\x10\n" +
	"\x03row\x18\x01 \x01(\rR\x03row\x12\x10\n" +
	"\x03col\x18\x02 \x01(\rR\x03col\"8\n" +
	"\n" +
	"EnumOption\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\"\xaf\x02\n" +
	"\vInputConfig\x123\n" +
	"\adecimal\x18\x01 \x01(\v2\x17.notbbg.v1.DecimalInputH\x00R\adecimal\x123\n" +
	"\ainteger\x18\x02 \x01(\v2\x17.notbbg.v1.IntegerInputH\x00R\ainteger\x12;\n" +
	"\fstring_input\x18\x03 \x01(\v2\x16.notbbg.v1.StringInputH\x00R\vstringInput\x125\n" +
	"\n" +
	"enum_input\x18\x04 \x01(\v2\x14.notbbg.v1.EnumInputH\x00R\tenumInput\x129\n" +
	"\tselection\x18\x05 \x01(\v2\x19.notbbg.v1.SelectionInputH\x00R\tselectionB\a\n" +
	"\x05input\"|\n" +
	"\fDecimalInput\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x01R\x05value\x12\x10\n" +
	"\x03min\x18\x02 \x01(\x01R\x03min\x12\x10\n" +
	"\x03max\x18\x03 \x01(\x01R\x03max\x12\x1c\n" +
	"\tprecision\x18\x04 \x01(\rR\tprecision\x12\x14\n" +
	"\x05label\x18\x05 \x01(\tR\x05label\"r\n" +
	"\fIntegerInput\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x03R\x05value\x12\x10\n" +
	"\x03min\x18\x02 \x01(\x03R\x03min\x12\x10\n" +
	"\x03max\x18\x03 \x01(\x03R\x03max\x12\x12\n" +
	"\x04step\x18\x04 \x01(\x03R\x04step\x12\x14\n" +
	"\x05label\x18\x05 \x01(\tR\x05label\"[\n" +
	"\vStringInput\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12 \n" +
	"\vplaceholder\x18\x02 \x01(\tR\vplaceholder\x12\x14\n" +
	"\x05label\x18\x03 \x01(\tR\x05label\"h\n" +
	"\tEnumInput\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12/\n" +
	"\aoptions\x18\x02 \x03(\v2\x15.notbbg.v1.EnumOptionR\aoptions\x12\x14\n" +
	"\x05label\x18\x03 \x01(\tR\x05label\"]\n" +
	"\x0eSelectionInput\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12\x1f\n" +
	"\vsearch_hint\x18\x03 \x01(\tR\n" +
	"searchHint\"\x82\x01\n" +
	"\fNumberOutput\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x01R\x05value\x12\x1c\n" +
	"\tprecision\x18\x02 \x01(\rR\tprecision\x12\x12\n" +
	"\x04unit\x18\x03 \x01(\tR\x04unit\x12\x14\n" +
	"\x05delta\x18\x04 \x01(\tR\x05delta\x12\x14\n" +
	"\x05label\x18\x05 \x01(\tR\x05label\"\x84\x01\n" +
	"\vFormulaCell\x12\x1e\n" +
	"\n" +
	"expression\x18\x01 \x01(\tR\n" +
	"expression\x12!\n" +
	"\fcached_value\x18\x02 \x01(\x01R\vcachedValue\x12\x1c\n" +
	"\tprecision\x18\x03 \x01(\rR\tprecision\x12\x14\n" +
	"\x05label\x18\x04 \x01(\tR\x05label\"\x95\x03\n" +
	"\x04Cell\x120\n" +
	"\aaddress\x18\x01 \x01(\v2\x16.notbbg.v1.CellAddressR\aaddress\x12*\n" +
	"\x05style\x18\x02 \x01(\v2\x14.notbbg.v1.CellStyleR\x05style\x12\x14\n" +
	"\x04text\x18\n" +
	" \x01(\tH\x00R\x04text\x12.\n" +
	"\x05input\x18\v \x01(\v2\x16.notbbg.v1.InputConfigH\x00R\x05input\x121\n" +
	"\x06number\x18\f \x01(\v2\x17.notbbg.v1.NumberOutputH\x00R\x06number\x122\n" +
	"\aformula\x18\r \x01(\v2\x16.notbbg.v1.FormulaCellH\x00R\aformula\x12\x1e\n" +
	"\tcomponent\x18\x0e \x01(\tH\x00R\tcomponent\x12!\n" +
	"\fvisible_when\x18\x14 \x01(\tR\vvisibleWhen\x12\x19\n" +
	"\bcol_span\x18\x15 \x01(\rR\acolSpan\x12\x19\n" +
	"\brow_span\x18\x16 \x01(\rR\arowSpanB\t\n" +
	"\acontent\"U\n" +
	"\x06Screen\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12%\n" +
	"\x05cells\x18\x03 \x03(\v2\x0f.notbbg.v1.CellR\x05cells\"u\n" +
	"\fScreenUpdate\x12\x1b\n" +
	"\tscreen_id\x18\x01 \x01(\tR\bscreenId\x12%\n" +
	"\x05cells\x18\x02 \x03(\v2\x0f.notbbg.v1.CellR\x05cells\x12!\n" +
	"\ffull_replace\x18\x03 \x01(\bR\vfullReplace\"\x89\x01\n" +
	"\x0ePluginRegister\x12\x1f\n" +
	"\vplugin_name\x18\x01 \x01(\tR\n" +
	"pluginName\x12+\n" +
	"\ascreens\x18\x02 \x03(\v2\x11.notbbg.v1.ScreenR\ascreens\x12)\n" +
	"\x10subscribe_topics\x18\x03 \x03(\tR\x0fsubscribeTopics\"z\n" +
	"\x0ePluginDataPush\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\"\xa9\x02\n" +
	"\x10PluginInputEvent\x12\x1b\n" +
	"\tscreen_id\x18\x01 \x01(\tR\bscreenId\x120\n" +
	"\aaddress\x18\x02 \x01(\v2\x16.notbbg.v1.CellAddressR\aaddress\x12%\n" +
	"\rdecimal_value\x18\n" +
	" \x01(\x01H\x00R\fdecimalValue\x12%\n" +
	"\rinteger_value\x18\v \x01(\x03H\x00R\fintegerValue\x12#\n" +
	"\fstring_value\x18\f \x01(\tH\x00R\vstringValue\x12\x1f\n" +
	"\n" +
	"enum_value\x18\r \x01(\tH\x00R\tenumValue\x12)\n" +
	"\x0fselection_value\x18\x0e \x01(\tH\x00R\x0eselectionValueB\a\n" +
	"\x05value\"\xbc\x01\n" +
	"\x0fPluginJobStatus\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x1b\n" +
	"\tscreen_id\x18\x02 \x01(\tR\bscreenId\x12)\n" +
	"\x05state\x18\x03 \x01(\x0e2\x13.notbbg.v1.JobStateR\x05state\x12\x1a\n" +
	"\bprogress\x18\x04 \x01(\x02R\bprogress\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\"\xb4\x02\n" +
	"\rPluginMessage\x127\n" +
	"\bregister\x18\x01 \x01(\v2\x19.notbbg.v1.PluginRegisterH\x00R\bregister\x121\n" +
	"\x06screen\x18\x02 \x01(\v2\x17.notbbg.v1.ScreenUpdateH\x00R\x06screen\x12/\n" +
	"\x04data\x18\x03 \x01(\v2\x19.notbbg.v1.PluginDataPushH\x00R\x04data\x12>\n" +
	"\vinput_event\x18\x04 \x01(\v2\x1b.notbbg.v1.PluginInputEventH\x00R\n" +
	"inputEvent\x12;\n" +
	"\n" +
	"job_status\x18\x05 \x01(\v2\x1a.notbbg.v1.PluginJobStatusH\x00R\tjobStatusB\t\n" +
	"\amessage*\x9b\x01\n" +
	"\bJobState\x12\x19\n" +
	"\x15JOB_STATE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11JOB_STATE_PENDING\x10\x01\x12\x15\n" +
	"\x11JOB_STATE_RUNNING\x10\x02\x12\x17\n" +
	"\x13JOB_STATE_COMPLETED\x10\x03\x12\x14\n" +
	"\x10JOB_STATE_FAILED\x10\x04\x12\x17\n" +
	"\x13JOB_STATE_CANCELLED\x10\x05B.Z,github.com/notbbg/notbbg/server/pkg/protocolb\x06proto3"

var (
	file_notbbg_v1_plugin_proto_rawDescOnce sync.Once
	file_notbbg_v1_plugin_proto_rawDescData []byte
)

func file_notbbg_v1_plugin_proto_rawDescGZIP() []byte {
	file_notbbg_v1_plugin_proto_rawDescOnce.Do(func() {
		file_notbbg_v1_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_notbbg_v1_plugin_proto_rawDesc), len(file_notbbg_v1_plugin_proto_rawDesc)))
	})
	return file_notbbg_v1_plugin_proto_rawDescData
}

var file_notbbg_v1_plugin_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_notbbg_v1_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_notbbg_v1_plugin_proto_goTypes = []any{
	(JobState)(0),                 // 0: notbbg.v1.JobState
	(*CellStyle)(nil),             // 1: notbbg.v1.CellStyle
	(*CellAddress)(nil),           // 2: notbbg.v1.CellAddress
	(*EnumOption)(nil),            // 3: notbbg.v1.EnumOption
	(*InputConfig)(nil),           // 4: notbbg.v1.InputConfig
	(*DecimalInput)(nil),          // 5: notbbg.v1.DecimalInput
	(*IntegerInput)(nil),          // 6: notbbg.v1.IntegerInput
	(*StringInput)(nil),           // 7: notbbg.v1.StringInput
	(*EnumInput)(nil),             // 8: notbbg.v1.EnumInput
	(*SelectionInput)(nil),        // 9: notbbg.v1.SelectionInput
	(*NumberOutput)(nil),          // 10: notbbg.v1.NumberOutput
	(*FormulaCell)(nil),           // 11: notbbg.v1.FormulaCell
	(*Cell)(nil),                  // 12: notbbg.v1.Cell
	(*Screen)(nil),                // 13: notbbg.v1.Screen
	(*ScreenUpdate)(nil),          // 14: notbbg.v1.ScreenUpdate
	(*PluginRegister)(nil),        // 15: notbbg.v1.PluginRegister
	(*PluginDataPush)(nil),        // 16: notbbg.v1.PluginDataPush
	(*PluginInputEvent)(nil),      // 17: notbbg.v1.PluginInputEvent
	(*PluginJobStatus)(nil),       // 18: notbbg.v1.PluginJobStatus
	(*PluginMessage)(nil),         // 19: notbbg.v1.PluginMessage
	(*timestamppb.Timestamp)(nil), // 20: google.protobuf.Timestamp
}
var file_notbbg_v1_plugin_proto_depIdxs = []int32{
	5,  // 0: notbbg.v1.InputConfig.decimal:type_name -> notbbg.v1.DecimalInput
	6,  // 1: notbbg.v1.InputConfig.integer:type_name -> notbbg.v1.IntegerInput
	7,  // 2: notbbg.v1.InputConfig.string_input:type_name -> notbbg.v1.StringInput
	8,  // 3: notbbg.v1.InputConfig.enum_input:type_name -> notbbg.v1.EnumInput
	9,  // 4: notbbg.v1.InputConfig.selection:type_name -> notbbg.v1.SelectionInput
	3,  // 5: notbbg.v1.EnumInput.options:type_name -> notbbg.v1.EnumOption
	2,  // 6: notbbg.v1.Cell.address:type_name -> notbbg.v1.CellAddress
	1,  // 7: notbbg.v1.Cell.style:type_name -> notbbg.v1.CellStyle
	4,  // 8: notbbg.v1.Cell.input:type_name -> notbbg.v1.InputConfig
	10, // 9: notbbg.v1.Cell.number:type_name -> notbbg.v1.NumberOutput
	11, // 10: notbbg.v1.Cell.formula:type_name -> notbbg.v1.FormulaCell
	12, // 11: notbbg.v1.Screen.cells:type_name -> notbbg.v1.Cell
	12, // 12: notbbg.v1.ScreenUpdate.cells:type_name -> notbbg.v1.Cell
	13, // 13: notbbg.v1.PluginRegister.screens:type_name -> notbbg.v1.Screen
	20, // 14: notbbg.v1.PluginDataPush.timestamp:type_name -> google.protobuf.Timestamp
	2,  // 15: notbbg.v1.PluginInputEvent.address:type_name -> notbbg.v1.CellAddress
	0,  // 16: notbbg.v1.PluginJobStatus.state:type_name -> notbbg.v1.JobState
	15, // 17: notbbg.v1.PluginMessage.register:type_name -> notbbg.v1.PluginRegister
	14, // 18: notbbg.v1.PluginMessage.screen:type_name -> notbbg.v1.ScreenUpdate
	16, // 19: notbbg.v1.PluginMessage.data:type_name -> notbbg.v1.PluginDataPush
	17, // 20: notbbg.v1.PluginMessage.input_event:type_name -> notbbg.v1.PluginInputEvent
	18, // 21: notbbg.v1.PluginMessage.job_status:type_name -> notbbg.v1.PluginJobStatus
	22, // [22:22] is the sub-list for method output_type
	22, // [22:22] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_notbbg_v1_plugin_proto_init() }
func file_notbbg_v1_plugin_proto_init() {
	if File_notbbg_v1_plugin_proto != nil {
		return
	}
	file_notbbg_v1_plugin_proto_msgTypes[3].OneofWrappers = []any{
		(*InputConfig_Decimal)(nil),
		(*InputConfig_Integer)(nil),
		(*InputConfig_StringInput)(nil),
		(*InputConfig_EnumInput)(nil),
		(*InputConfig_Selection)(nil),
	}
	file_notbbg_v1_plugin_proto_msgTypes[11].OneofWrappers = []any{
		(*Cell_Text)(nil),
		(*Cell_Input)(nil),
		(*Cell_Number)(nil),
		(*Cell_Formula)(nil),
		(*Cell_Component)(nil),
	}
	file_notbbg_v1_plugin_proto_msgTypes[16].OneofWrappers = []any{
		(*PluginInputEvent_DecimalValue)(nil),
		(*PluginInputEvent_IntegerValue)(nil),
		(*PluginInputEvent_StringValue)(nil),
		(*PluginInputEvent_EnumValue)(nil),
		(*PluginInputEvent_SelectionValue)(nil),
	}
	file_notbbg_v1_plugin_proto_msgTypes[18].OneofWrappers = []any{
		(*PluginMessage_Register)(nil),
		(*PluginMessage_Screen)(nil),
		(*PluginMessage_Data)(nil),
		(*PluginMessage_InputEvent)(nil),
		(*PluginMessage_JobStatus)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_notbbg_v1_plugin_proto_rawDesc), len(file_notbbg_v1_plugin_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_notbbg_v1_plugin_proto_goTypes,
		DependencyIndexes: file_notbbg_v1_plugin_proto_depIdxs,
		EnumInfos:         file_notbbg_v1_plugin_proto_enumTypes,
		MessageInfos:      file_notbbg_v1_plugin_proto_msgTypes,
	}.Build()
	File_notbbg_v1_plugin_proto = out.File
	file_notbbg_v1_plugin_proto_goTypes = nil
	file_notbbg_v1_plugin_proto_depIdxs = nil
}
