// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: notbbg/v1/server.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QueryType int32

const (
	QueryType_QUERY_TYPE_UNSPECIFIED QueryType = 0
	QueryType_QUERY_TYPE_OHLC        QueryType = 1
	QueryType_QUERY_TYPE_TRADES      QueryType = 2
	QueryType_QUERY_TYPE_LOB         QueryType = 3
	QueryType_QUERY_TYPE_NEWS        QueryType = 4
	QueryType_QUERY_TYPE_ALERTS      QueryType = 5
)

// Enum value maps for QueryType.
var (
	QueryType_name = map[int32]string{
		0: "QUERY_TYPE_UNSPECIFIED",
		1: "QUERY_TYPE_OHLC",
		2: "QUERY_TYPE_TRADES",
		3: "QUERY_TYPE_LOB",
		4: "QUERY_TYPE_NEWS",
		5: "QUERY_TYPE_ALERTS",
	}
	QueryType_value = map[string]int32{
		"QUERY_TYPE_UNSPECIFIED": 0,
		"QUERY_TYPE_OHLC":        1,
		"QUERY_TYPE_TRADES":      2,
		"QUERY_TYPE_LOB":         3,
		"QUERY_TYPE_NEWS":        4,
		"QUERY_TYPE_ALERTS":      5,
	}
)

func (x QueryType) Enum() *QueryType {
	p := new(QueryType)
	*p = x
	return p
}

func (x QueryType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (QueryType) Descriptor() protoreflect.EnumDescriptor {
	return file_notbbg_v1_server_proto_enumTypes[0].Descriptor()
}

func (QueryType) Type() protoreflect.EnumType {
	return &file_notbbg_v1_server_proto_enumTypes[0]
}

func (x QueryType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use QueryType.Descriptor instead.
func (QueryType) EnumDescriptor() ([]byte, []int) {
	return file_notbbg_v1_server_proto_rawDescGZIP(), []int{0}
}

type ExportFormat int32

const (
	ExportFormat_EXPORT_FORMAT_UNSPECIFIED ExportFormat = 0
	ExportFormat_EXPORT_FORMAT_JSON        ExportFormat = 1
	ExportFormat_EXPORT_FORMAT_JSONL       ExportFormat = 2
	ExportFormat_EXPORT_FORMAT_CSV         ExportFormat = 3
)

// Enum value maps for ExportFormat.
var (
	ExportFormat_name = map[int32]string{
		0: "EXPORT_FORMAT_UNSPECIFIED",
		1: "EXPORT_FORMAT_JSON",
		2: "EXPORT_FORMAT_JSONL",
		3: "EXPORT_FORMAT_CSV",
	}
	ExportFormat_value = map[string]int32{
		"EXPORT_FORMAT_UNSPECIFIED": 0,
		"EXPORT_FORMAT_JSON":        1,
		"EXPORT_FORMAT_JSONL":       2,
		"EXPORT_FORMAT_CSV":         3,
	}
)

func (x ExportFormat) Enum() *ExportFormat {
	p := new(ExportFormat)
	*p = x
	return p
}

func (x ExportFormat) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExportFormat) Descriptor() protoreflect.EnumDescriptor {
	return file_notbbg_v1_server_proto_enumTypes[1].Descriptor()
}

func (ExportFormat) Type() protoreflect.EnumType {
	return &file_notbbg_v1_server_proto_enumTypes[1]
}

func (x ExportFormat) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExportFormat.Descriptor instead.
func (ExportFormat) EnumDescriptor() ([]byte, []int) {
	return file_notbbg_v1_server_proto_rawDescGZIP(), []int{1}
}

type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subscriptions []*Subscription        `protobuf:"bytes,1,rep,name=subscriptions,proto3" json:"subscriptions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_notbbg_v1_server_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notbbg_v1_server_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_notbbg_v1_server_proto_rawDescGZIP(), []int{0}
}

func (x *SubscribeRequest) GetSubscriptions() []*Subscription {
	if x != nil {
		return x.Subscriptions
	}
	return nil
}

type SubscribeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Update        *Update                `protobuf:"bytes,1,opt,name=update,proto3" json:"update,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeResponse) Reset() {
	*x = SubscribeResponse{}
	mi := &file_notbbg_v1_server_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeResponse) ProtoMessage() {}

func (x *SubscribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notbbg_v1_server_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeResponse.ProtoReflect.Descriptor instead.
func (*SubscribeResponse) Descriptor() ([]byte, []int) {
	return file_notbbg_v1_server_proto_rawDescGZIP(), []int{1}
}

func (x *SubscribeResponse) GetUpdate() *Update {
	if x != nil {
		return x.Update
	}
	return nil
}

type QueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          QueryType              `protobuf:"varint,1,opt,name=type,proto3,enum=notbbg.v1.QueryType" json:"type,omitempty"`
	Instrument    string                 `protobuf:"bytes,2,opt,name=instrument,proto3" json:"instrument,omitempty"`
	Exchange      string                 `protobuf:"bytes,3,opt,name=exchange,proto3" json:"exchange,omitempty"`
	Timeframe     string                 `protobuf:"bytes,4,opt,name=timeframe,proto3" json:"timeframe,omitempty"`
	From          *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=from,proto3" json:"from,omitempty"`
	To            *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=to,proto3" json:"to,omitempty"`
	Query         string                 `protobuf:"bytes,7,opt,name=query,proto3" json:"query,omitempty"`
	Limit         int32                  `protobuf:"varint,8,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRequest) Reset() {
	*x = QueryRequest{}
	mi := &file_notbbg_v1_server_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRequest) ProtoMessage() {}

func (x *QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notbbg_v1_server_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRequest.ProtoReflect.Descriptor instead.
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return file_notbbg_v1_server_proto_rawDescGZIP(), []int{2}
}

func (x *QueryRequest) GetType() QueryType {
	if x != nil {
		return x.Type
	}
	return QueryType_QUERY_TYPE_UNSPECIFIED
}

func (x *QueryRequest) GetInstrument() string {
	if x != nil {
		return x.Instrument
	}
	return ""
}

func (x *QueryRequest) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

func (x *QueryRequest) GetTimeframe() string {
	if x != nil {
		return x.Timeframe
	}
	return ""
}

func (x *QueryRequest) GetFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *QueryRequest) GetTo() *timestamppb.Timestamp {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *QueryRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *QueryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type QueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ohlc          []*OHLC                `protobuf:"bytes,1,rep,name=ohlc,proto3" json:"ohlc,omitempty"`
	Trades        []*Trade               `protobuf:"bytes,2,rep,name=trades,proto3" json:"trades,omitempty"`
	Lob           []*LOBSnapshot         `protobuf:"bytes,3,rep,name=lob,proto3" json:"lob,omitempty"`
	News          []*NewsItem            `protobuf:"bytes,4,rep,name=news,proto3" json:"news,omitempty"`
	Alerts        []*Alert               `protobuf:"bytes,5,rep,name=alerts,proto3" json:"alerts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResponse) Reset() {
	*x = QueryResponse{}
	mi := &file_notbbg_v1_server_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResponse) ProtoMessage() {}

func (x *QueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notbbg_v1_server_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResponse.ProtoReflect.Descriptor instead.
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return file_notbbg_v1_server_proto_rawDescGZIP(), []int{3}
}

func (x *QueryResponse) GetOhlc() []*OHLC {
	if x != nil {
		return x.Ohlc
	}
	return nil
}

func (x *QueryResponse) GetTrades() []*Trade {
	if x != nil {
		return x.Trades
	}
	return nil
}

func (x *QueryResponse) GetLob() []*LOBSnapshot {
	if x != nil {
		return x.Lob
	}
	return nil
}

func (x *QueryResponse) GetNews() []*NewsItem {
	if x != nil {
		return x.News
	}
	return nil
}

func (x *QueryResponse) GetAlerts() []*Alert {
	if x != nil {
		return x.Alerts
	}
	return nil
}

// GetDataRangeRequest — client asks the server to stream a time window
// of historical data for a topic. See DATA-PLAN.md §3. Named per
// buf's STANDARD lint rule ("RPC request types should be named
// <Method>Request"); semantically this is a data-range request.
type GetDataRangeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"` // e.g. "ohlc.binance.BTCUSDT"
	From          *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To            *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	Resolution    string                 `protobuf:"bytes,4,opt,name=resolution,proto3" json:"resolution,omitempty"`                            // e.g. "1m", "1h", "1d"
	CorrelationId string                 `protobuf:"bytes,5,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"` // client-supplied ID for progress + cancellation
	MaxRecords    int32                  `protobuf:"varint,6,opt,name=max_records,json=maxRecords,proto3" json:"max_records,omitempty"`         // 0 = server default cap
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDataRangeRequest) Reset() {
	*x = GetDataRangeRequest{}
	mi := &file_notbbg_v1_server_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDataRangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDataRangeRequest) ProtoMessage() {}

func (x *GetDataRangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notbbg_v1_server_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDataRangeRequest.ProtoReflect.Descriptor instead.
func (*GetDataRangeRequest) Descriptor() ([]byte, []int) {
	return file_notbbg_v1_server_proto_rawDescGZIP(), []int{4}
}

func (x *GetDataRangeRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *GetDataRangeRequest) GetFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *GetDataRangeRequest) GetTo() *timestamppb.Timestamp {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *GetDataRangeRequest) GetResolution() string {
	if x != nil {
		return x.Resolution
	}
	return ""
}

func (x *GetDataRangeRequest) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *GetDataRangeRequest) GetMaxRecords() int32 {
	if x != nil {
		return x.MaxRecords
	}
	return 0
}

// GetDataRangeResponse — one streamed chunk. Final chunk has eof=true.
// Named per buf's STANDARD lint rule; semantically each message is a
// progress chunk, not a single response.
type GetDataRangeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId string                 `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	Records       []*Update              `protobuf:"bytes,2,rep,name=records,proto3" json:"records,omitempty"`
	Seq           int32                  `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"` // 0-based chunk index; useful for "loading N/M"
	Eof           bool                   `protobuf:"varint,4,opt,name=eof,proto3" json:"eof,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDataRangeResponse) Reset() {
	*x = GetDataRangeResponse{}
	mi := &file_notbbg_v1_server_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDataRangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDataRangeResponse) ProtoMessage() {}

func (x *GetDataRangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notbbg_v1_server_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDataRangeResponse.ProtoReflect.Descriptor instead.
func (*GetDataRangeResponse) Descriptor() ([]byte, []int) {
	return file_notbbg_v1_server_proto_rawDescGZIP(), []int{5}
}

func (x *GetDataRangeResponse) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *GetDataRangeResponse) GetRecords() []*Update {
	if x != nil {
		return x.Records
	}
	return nil
}

func (x *GetDataRangeResponse) GetSeq() int32 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *GetDataRangeResponse) GetEof() bool {
	if x != nil {
		return x.Eof
	}
	return false
}

// DataRangeError — a terminal error for a correlation_id, sent by the
// server before closing the stream. Not an RPC request/response type
// (not referenced in a service definition), so the STANDARD lint rule
// does not apply.
type DataRangeError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId string                 `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataRangeError) Reset() {
	*x = DataRangeError{}
	mi := &file_notbbg_v1_server_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataRangeError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataRangeError) ProtoMessage() {}

func (x *DataRangeError) ProtoReflect() protoreflect.Message {
	mi := &file_notbbg_v1_server_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataRangeError.ProtoReflect.Descriptor instead.
func (*DataRangeError) Descriptor() ([]byte, []int) {
	return file_notbbg_v1_server_proto_rawDescGZIP(), []int{6}
}

func (x *DataRangeError) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *DataRangeError) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ExportDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         *QueryRequest          `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Format        ExportFormat           `protobuf:"varint,2,opt,name=format,proto3,enum=notbbg.v1.ExportFormat" json:"format,omitempty"`
	Gzip          bool                   `protobuf:"varint,3,opt,name=gzip,proto3" json:"gzip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportDataRequest) Reset() {
	*x = ExportDataRequest{}
	mi := &file_notbbg_v1_server_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportDataRequest) ProtoMessage() {}

func (x *ExportDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notbbg_v1_server_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportDataRequest.ProtoReflect.Descriptor instead.
func (*ExportDataRequest) Descriptor() ([]byte, []int) {
	return file_notbbg_v1_server_proto_rawDescGZIP(), []int{7}
}

func (x *ExportDataRequest) GetQuery() *QueryRequest {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *ExportDataRequest) GetFormat() ExportFormat {
	if x != nil {
		return x.Format
	}
	return ExportFormat_EXPORT_FORMAT_UNSPECIFIED
}

func (x *ExportDataRequest) GetGzip() bool {
	if x != nil {
		return x.Gzip
	}
	return false
}

type ExportDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportDataResponse) Reset() {
	*x = ExportDataResponse{}
	mi := &file_notbbg_v1_server_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportDataResponse) ProtoMessage() {}

func (x *ExportDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notbbg_v1_server_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportDataResponse.ProtoReflect.Descriptor instead.
func (*ExportDataResponse) Descriptor() ([]byte, []int) {
	return file_notbbg_v1_server_proto_rawDescGZIP(), []int{8}
}

func (x *ExportDataResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetFeedStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFeedStatusRequest) Reset() {
	*x = GetFeedStatusRequest{}
	mi := &file_notbbg_v1_server_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFeedStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFeedStatusRequest) ProtoMessage() {}

func (x *GetFeedStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notbbg_v1_server_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFeedStatusRequest.ProtoReflect.Descriptor instead.
func (*GetFeedStatusRequest) Descriptor() ([]byte, []int) {
	return file_notbbg_v1_server_proto_rawDescGZIP(), []int{9}
}

type GetFeedStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Feeds         []*FeedStatus          `protobuf:"bytes,1,rep,name=feeds,proto3" json:"feeds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFeedStatusResponse) Reset() {
	*x = GetFeedStatusResponse{}
	mi := &file_notbbg_v1_server_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFeedStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFeedStatusResponse) ProtoMessage() {}

func (x *GetFeedStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notbbg_v1_server_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFeedStatusResponse.ProtoReflect.Descriptor instead.
func (*GetFeedStatusResponse) Descriptor() ([]byte, []int) {
	return file_notbbg_v1_server_proto_rawDescGZIP(), []int{10}
}

func (x *GetFeedStatusResponse) GetFeeds() []*FeedStatus {
	if x != nil {
		return x.Feeds
	}
	return nil
}

var File_notbbg_v1_server_proto protoreflect.FileDescriptor

const file_notbbg_v1_server_proto_rawDesc = "" +
	"\n" +
	"\x16notbbg/v1/server.proto\x12\tnotbbg.v1\x1a\x15notbbg/v1/types.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"Q\n" +
	"\x10SubscribeRequest\x12=\n" +
	"\rsubscriptions\x18\x01 \x03(\v2\x17.notbbg.v1.SubscriptionR\rsubscriptions\">\n" +
	"\x11SubscribeResponse\x12)\n" +
	"\x06update\x18\x01 \x01(\v2\x11.notbbg.v1.UpdateR\x06update\"\x9a\x02\n" +
	"\fQueryRequest\x12(\n" +
	"\x04type\x18\x01 \x01(\x0e2\x14.notbbg.v1.QueryTypeR\x04type\x12\x1e\n" +
	"\n" +
	"instrument\x18\x02 \x01(\tR\n" +
	"instrument\x12\x1a\n" +
	"\bexchange\x18\x03 \x01(\tR\bexchange\x12\x1c\n" +
	"\ttimeframe\x18\x04 \x01(\tR\ttimeframe\x12.\n" +
	"\x04from\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x04from\x12*\n" +
	"\x02to\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x02to\x12\x14\n" +
	"\x05query\x18\a \x01(\tR\x05query\x12\x14\n" +
	"\x05limit\x18\b \x01(\x05R\x05limit\"\xdb\x01\n" +
	"\rQueryResponse\x12#\n" +
	"\x04ohlc\x18\x01 \x03(\v2\x0f.notbbg.v1.OHLCR\x04ohlc\x12(\n" +
	"\x06trades\x18\x02 \x03(\v2\x10.notbbg.v1.TradeR\x06trades\x12(\n" +
	"\x03lob\x18\x03 \x03(\v2\x16.notbbg.v1.LOBSnapshotR\x03lob\x12'\n" +
	"\x04news\x18\x04 \x03(\v2\x13.notbbg.v1.NewsItemR\x04news\x12(\n" +
	"\x06alerts\x18\x05 \x03(\v2\x10.notbbg.v1.AlertR\x06alerts\"\xef\x01\n" +
	"\x13GetDataRangeRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12.\n" +
	"\x04from\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x04from\x12*\n" +
	"\x02to\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x02to\x12\x1e\n" +
	"\n" +
	"resolution\x18\x04 \x01(\tR\n" +
	"resolution\x12%\n" +
	"\x0ecorrelation_id\x18\x05 \x01(\tR\rcorrelationId\x12\x1f\n" +
	"\vmax_records\x18\x06 \x01(\x05R\n" +
	"maxRecords\"\x8e\x01\n" +
	"\x14GetDataRangeResponse\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\tR\rcorrelationId\x12+\n" +
	"\arecords\x18\x02 \x03(\v2\x11.notbbg.v1.UpdateR\arecords\x12\x10\n" +
	"\x03seq\x18\x03 \x01(\x05R\x03seq\x12\x10\n" +
	"\x03eof\x18\x04 \x01(\bR\x03eof\"O\n" +
	"\x0eDataRangeError\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\tR\rcorrelationId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\x87\x01\n" +
	"\x11ExportDataRequest\x12-\n" +
	"\x05query\x18\x01 \x01(\v2\x17.notbbg.v1.QueryRequestR\x05query\x12/\n" +
	"\x06format\x18\x02 \x01(\x0e2\x17.notbbg.v1.ExportFormatR\x06format\x12\x12\n" +
	"\x04gzip\x18\x03 \x01(\bR\x04gzip\"(\n" +
	"\x12ExportDataResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"\x16\n" +
	"\x14GetFeedStatusRequest\"D\n" +
	"\x15GetFeedStatusResponse\x12+\n" +
	"\x05feeds\x18\x01 \x03(\v2\x15.notbbg.v1.FeedStatusR\x05feeds*\x93\x01\n" +
	"\tQueryType\x12\x1a\n" +
	"\x16QUERY_TYPE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fQUERY_TYPE_OHLC\x10\x01\x12\x15\n" +
	"\x11QUERY_TYPE_TRADES\x10\x02\x12\x12\n" +
	"\x0eQUERY_TYPE_LOB\x10\x03\x12\x13\n" +
	"\x0fQUERY_TYPE_NEWS\x10\x04\x12\x15\n" +
	"\x11QUERY_TYPE_ALERTS\x10\x05*u\n" +
	"\fExportFormat\x12\x1d\n" +
	"\x19EXPORT_FORMAT_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12EXPORT_FORMAT_JSON\x10\x01\x12\x17\n" +
	"\x13EXPORT_FORMAT_JSONL\x10\x02\x12\x15\n" +
	"\x11EXPORT_FORMAT_CSV\x10\x032\x87\x03\n" +
	"\vDataService\x12H\n" +
	"\tSubscribe\x12\x1b.notbbg.v1.SubscribeRequest\x1a\x1c.notbbg.v1.SubscribeResponse0\x01\x12:\n" +
	"\x05Query\x12\x17.notbbg.v1.QueryRequest\x1a\x18.notbbg.v1.QueryResponse\x12Q\n" +
	"\fGetDataRange\x12\x1e.notbbg.v1.GetDataRangeRequest\x1a\x1f.notbbg.v1.GetDataRangeResponse0\x01\x12K\n" +
	"\n" +
	"ExportData\x12\x1c.notbbg.v1.ExportDataRequest\x1a\x1d.notbbg.v1.ExportDataResponse0\x01\x12R\n" +
	"\rGetFeedStatus\x12\x1f.notbbg.v1.GetFeedStatusRequest\x1a .notbbg.v1.GetFeedStatusResponseB.Z,github.com/notbbg/notbbg/server/pkg/protocolb\x06proto3"

var (
	file_notbbg_v1_server_proto_rawDescOnce sync.Once
	file_notbbg_v1_server_proto_rawDescData []byte
)

func file_notbbg_v1_server_proto_rawDescGZIP() []byte {
	file_notbbg_v1_server_proto_rawDescOnce.Do(func() {
		file_notbbg_v1_server_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_notbbg_v1_server_proto_rawDesc), len(file_notbbg_v1_server_proto_rawDesc)))
	})
	return file_notbbg_v1_server_proto_rawDescData
}

var file_notbbg_v1_server_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_notbbg_v1_server_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_notbbg_v1_server_proto_goTypes = []any{
	(QueryType)(0),                // 0: notbbg.v1.QueryType
	(ExportFormat)(0),             // 1: notbbg.v1.ExportFormat
	(*SubscribeRequest)(nil),      // 2: notbbg.v1.SubscribeRequest
	(*SubscribeResponse)(nil),     // 3: notbbg.v1.SubscribeResponse
	(*QueryRequest)(nil),          // 4: notbbg.v1.QueryRequest
	(*QueryResponse)(nil),         // 5: notbbg.v1.QueryResponse
	(*GetDataRangeRequest)(nil),   // 6: notbbg.v1.GetDataRangeRequest
	(*GetDataRangeResponse)(nil),  // 7: notbbg.v1.GetDataRangeResponse
	(*DataRangeError)(nil),        // 8: notbbg.v1.DataRangeError
	(*ExportDataRequest)(nil),     // 9: notbbg.v1.ExportDataRequest
	(*ExportDataResponse)(nil),    // 10: notbbg.v1.ExportDataResponse
	(*GetFeedStatusRequest)(nil),  // 11: notbbg.v1.GetFeedStatusRequest
	(*GetFeedStatusResponse)(nil), // 12: notbbg.v1.GetFeedStatusResponse
	(*Subscription)(nil),          // 13: notbbg.v1.Subscription
	(*Update)(nil),                // 14: notbbg.v1.Update
	(*timestamppb.Timestamp)(nil), // 15: google.protobuf.Timestamp
	(*OHLC)(nil),                  // 16: notbbg.v1.OHLC
	(*Trade)(nil),                 // 17: notbbg.v1.Trade
	(*LOBSnapshot)(nil),           // 18: notbbg.v1.LOBSnapshot
	(*NewsItem)(nil),              // 19: notbbg.v1.NewsItem
	(*Alert)(nil),                 // 20: notbbg.v1.Alert
	(*FeedStatus)(nil),            // 21: notbbg.v1.FeedStatus
}
var file_notbbg_v1_server_proto_depIdxs = []int32{
	13, // 0: notbbg.v1.SubscribeRequest.subscriptions:type_name -> notbbg.v1.Subscription
	14, // 1: notbbg.v1.SubscribeResponse.update:type_name -> notbbg.v1.Update
	0,  // 2: notbbg.v1.QueryRequest.type:type_name -> notbbg.v1.QueryType
	15, // 3: notbbg.v1.QueryRequest.from:type_name -> google.protobuf.Timestamp
	15, // 4: notbbg.v1.QueryRequest.to:type_name -> google.protobuf.Timestamp
	16, // 5: notbbg.v1.QueryResponse.ohlc:type_name -> notbbg.v1.OHLC
	17, // 6: notbbg.v1.QueryResponse.trades:type_name -> notbbg.v1.Trade
	18, // 7: notbbg.v1.QueryResponse.lob:type_name -> notbbg.v1.LOBSnapshot
	19, // 8: notbbg.v1.QueryResponse.news:type_name -> notbbg.v1.NewsItem
	20, // 9: notbbg.v1.QueryResponse.alerts:type_name -> notbbg.v1.Alert
	15, // 10: notbbg.v1.GetDataRangeRequest.from:type_name -> google.protobuf.Timestamp
	15, // 11: notbbg.v1.GetDataRangeRequest.to:type_name -> google.protobuf.Timestamp
	14, // 12: notbbg.v1.GetDataRangeResponse.records:type_name -> notbbg.v1.Update
	4,  // 13: notbbg.v1.ExportDataRequest.query:type_name -> notbbg.v1.QueryRequest
	1,  // 14: notbbg.v1.ExportDataRequest.format:type_name -> notbbg.v1.ExportFormat
	21, // 15: notbbg.v1.GetFeedStatusResponse.feeds:type_name -> notbbg.v1.FeedStatus
	2,  // 16: notbbg.v1.DataService.Subscribe:input_type -> notbbg.v1.SubscribeRequest
	4,  // 17: notbbg.v1.DataService.Query:input_type -> notbbg.v1.QueryRequest
	6,  // 18: notbbg.v1.DataService.GetDataRange:input_type -> notbbg.v1.GetDataRangeRequest
	9,  // 19: notbbg.v1.DataService.ExportData:input_type -> notbbg.v1.ExportDataRequest
	11, // 20: notbbg.v1.DataService.GetFeedStatus:input_type -> notbbg.v1.GetFeedStatusRequest
	3,  // 21: notbbg.v1.DataService.Subscribe:output_type -> notbbg.v1.SubscribeResponse
	5,  // 22: notbbg.v1.DataService.Query:output_type -> notbbg.v1.QueryResponse
	7,  // 23: notbbg.v1.DataService.GetDataRange:output_type -> notbbg.v1.GetDataRangeResponse
	10, // 24: notbbg.v1.DataService.ExportData:output_type -> notbbg.v1.ExportDataResponse
	12, // 25: notbbg.v1.DataService.GetFeedStatus:output_type -> notbbg.v1.GetFeedStatusResponse
	21, // [21:26] is the sub-list for method output_type
	16, // [16:21] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_notbbg_v1_server_proto_init() }
func file_notbbg_v1_server_proto_init() {
	if File_notbbg_v1_server_proto != nil {
		return
	}
	file_notbbg_v1_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_notbbg_v1_server_proto_rawDesc), len(file_notbbg_v1_server_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_notbbg_v1_server_proto_goTypes,
		DependencyIndexes: file_notbbg_v1_server_proto_depIdxs,
		EnumInfos:         file_notbbg_v1_server_proto_enumTypes,
		MessageInfos:      file_notbbg_v1_server_proto_msgTypes,
	}.Build()
	File_notbbg_v1_server_proto = out.File
	file_notbbg_v1_server_proto_goTypes = nil
	file_notbbg_v1_server_proto_depIdxs = nil
}
