// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: notbbg/v1/server.proto

package protocol

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DataService_Subscribe_FullMethodName     = "/notbbg.v1.DataService/Subscribe"
	DataService_Query_FullMethodName         = "/notbbg.v1.DataService/Query"
	DataService_GetDataRange_FullMethodName  = "/notbbg.v1.DataService/GetDataRange"
	DataService_ExportData_FullMethodName    = "/notbbg.v1.DataService/ExportData"
	DataService_GetFeedStatus_FullMethodName = "/notbbg.v1.DataService/GetFeedStatus"
)

// DataServiceClient is the client API for DataService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Main data service for subscribing to feeds and querying cached data.
type DataServiceClient interface {
	// Subscribe to real-time updates matching the given subscriptions.
	Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SubscribeResponse], error)
	// Query historical data from the cache.
	Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error)
	// GetDataRange streams a window of historical data for a topic,
	// chunked so the client can render progressively and cancel via the
	// request's correlation_id (or standard gRPC context cancellation).
	// Cache is checked first, then datalake. See DATA-PLAN.md §3.
	GetDataRange(ctx context.Context, in *GetDataRangeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetDataRangeResponse], error)
	// Export data in bulk (JSON, JSONL, CSV).
	ExportData(ctx context.Context, in *ExportDataRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExportDataResponse], error)
	// Get current status of all data feeds.
	GetFeedStatus(ctx context.Context, in *GetFeedStatusRequest, opts ...grpc.CallOption) (*GetFeedStatusResponse, error)
}

type dataServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDataServiceClient(cc grpc.ClientConnInterface) DataServiceClient {
	return &dataServiceClient{cc}
}

func (c *dataServiceClient) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SubscribeResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DataService_ServiceDesc.Streams[0], DataService_Subscribe_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeRequest, SubscribeResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataService_SubscribeClient = grpc.ServerStreamingClient[SubscribeResponse]

func (c *dataServiceClient) Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryResponse)
	err := c.cc.Invoke(ctx, DataService_Query_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataServiceClient) GetDataRange(ctx context.Context, in *GetDataRangeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetDataRangeResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DataService_ServiceDesc.Streams[1], DataService_GetDataRange_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetDataRangeRequest, GetDataRangeResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataService_GetDataRangeClient = grpc.ServerStreamingClient[GetDataRangeResponse]

func (c *dataServiceClient) ExportData(ctx context.Context, in *ExportDataRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExportDataResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DataService_ServiceDesc.Streams[2], DataService_ExportData_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ExportDataRequest, ExportDataResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataService_ExportDataClient = grpc.ServerStreamingClient[ExportDataResponse]

func (c *dataServiceClient) GetFeedStatus(ctx context.Context, in *GetFeedStatusRequest, opts ...grpc.CallOption) (*GetFeedStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFeedStatusResponse)
	err := c.cc.Invoke(ctx, DataService_GetFeedStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DataServiceServer is the server API for DataService service.
// All implementations must embed UnimplementedDataServiceServer
// for forward compatibility.
//
// Main data service for subscribing to feeds and querying cached data.
type DataServiceServer interface {
	// Subscribe to real-time updates matching the given subscriptions.
	Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[SubscribeResponse]) error
	// Query historical data from the cache.
	Query(context.Context, *QueryRequest) (*QueryResponse, error)
	// GetDataRange streams a window of historical data for a topic,
	// chunked so the client can render progressively and cancel via the
	// request's correlation_id (or standard gRPC context cancellation).
	// Cache is checked first, then datalake. See DATA-PLAN.md §3.
	GetDataRange(*GetDataRangeRequest, grpc.ServerStreamingServer[GetDataRangeResponse]) error
	// Export data in bulk (JSON, JSONL, CSV).
	ExportData(*ExportDataRequest, grpc.ServerStreamingServer[ExportDataResponse]) error
	// Get current status of all data feeds.
	GetFeedStatus(context.Context, *GetFeedStatusRequest) (*GetFeedStatusResponse, error)
	mustEmbedUnimplementedDataServiceServer()
}

// UnimplementedDataServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDataServiceServer struct{}

func (UnimplementedDataServiceServer) Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[SubscribeResponse]) error {
	return status.Error(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedDataServiceServer) Query(context.Context, *QueryRequest) (*QueryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Query not implemented")
}
func (UnimplementedDataServiceServer) GetDataRange(*GetDataRangeRequest, grpc.ServerStreamingServer[GetDataRangeResponse]) error {
	return status.Error(codes.Unimplemented, "method GetDataRange not implemented")
}
func (UnimplementedDataServiceServer) ExportData(*ExportDataRequest, grpc.ServerStreamingServer[ExportDataResponse]) error {
	return status.Error(codes.Unimplemented, "method ExportData not implemented")
}
func (UnimplementedDataServiceServer) GetFeedStatus(context.Context, *GetFeedStatusRequest) (*GetFeedStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFeedStatus not implemented")
}
func (UnimplementedDataServiceServer) mustEmbedUnimplementedDataServiceServer() {}
func (UnimplementedDataServiceServer) testEmbeddedByValue()                     {}

// UnsafeDataServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DataServiceServer will
// result in compilation errors.
type UnsafeDataServiceServer interface {
	mustEmbedUnimplementedDataServiceServer()
}

func RegisterDataServiceServer(s grpc.ServiceRegistrar, srv DataServiceServer) {
	// If the following call panics, it indicates UnimplementedDataServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DataService_ServiceDesc, srv)
}

func _DataService_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DataServiceServer).Subscribe(m, &grpc.GenericServerStream[SubscribeRequest, SubscribeResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataService_SubscribeServer = grpc.ServerStreamingServer[SubscribeResponse]

func _DataService_Query_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataServiceServer).Query(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataService_Query_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataServiceServer).Query(ctx, req.(*QueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataService_GetDataRange_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetDataRangeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DataServiceServer).GetDataRange(m, &grpc.GenericServerStream[GetDataRangeRequest, GetDataRangeResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataService_GetDataRangeServer = grpc.ServerStreamingServer[GetDataRangeResponse]

func _DataService_ExportData_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ExportDataRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DataServiceServer).ExportData(m, &grpc.GenericServerStream[ExportDataRequest, ExportDataResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataService_ExportDataServer = grpc.ServerStreamingServer[ExportDataResponse]

func _DataService_GetFeedStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFeedStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataServiceServer).GetFeedStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataService_GetFeedStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataServiceServer).GetFeedStatus(ctx, req.(*GetFeedStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DataService_ServiceDesc is the grpc.ServiceDesc for DataService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DataService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "notbbg.v1.DataService",
	HandlerType: (*DataServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Query",
			Handler:    _DataService_Query_Handler,
		},
		{
			MethodName: "GetFeedStatus",
			Handler:    _DataService_GetFeedStatus_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _DataService_Subscribe_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetDataRange",
			Handler:       _DataService_GetDataRange_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ExportData",
			Handler:       _DataService_ExportData_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "notbbg/v1/server.proto",
}
