// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: notbbg/v1/types.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Side int32

const (
	Side_SIDE_UNSPECIFIED Side = 0
	Side_SIDE_BUY         Side = 1
	Side_SIDE_SELL        Side = 2
)

// Enum value maps for Side.
var (
	Side_name = map[int32]string{
		0: "SIDE_UNSPECIFIED",
		1: "SIDE_BUY",
		2: "SIDE_SELL",
	}
	Side_value = map[string]int32{
		"SIDE_UNSPECIFIED": 0,
		"SIDE_BUY":         1,
		"SIDE_SELL":        2,
	}
)

func (x Side) Enum() *Side {
	p := new(Side)
	*p = x
	return p
}

func (x Side) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Side) Descriptor() protoreflect.EnumDescriptor {
	return file_notbbg_v1_types_proto_enumTypes[0].Descriptor()
}

func (Side) Type() protoreflect.EnumType {
	return &file_notbbg_v1_types_proto_enumTypes[0]
}

func (x Side) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Side.Descriptor instead.
func (Side) EnumDescriptor() ([]byte, []int) {
	return file_notbbg_v1_types_proto_rawDescGZIP(), []int{0}
}

type AlertType int32

const (
	AlertType_ALERT_TYPE_UNSPECIFIED  AlertType = 0
	AlertType_ALERT_TYPE_PRICE_ABOVE  AlertType = 1
	AlertType_ALERT_TYPE_PRICE_BELOW  AlertType = 2
	AlertType_ALERT_TYPE_VOLUME_SPIKE AlertType = 3
	AlertType_ALERT_TYPE_KEYWORD      AlertType = 4
	AlertType_ALERT_TYPE_FEED_DOWN    AlertType = 5
)

// Enum value maps for AlertType.
var (
	AlertType_name = map[int32]string{
		0: "ALERT_TYPE_UNSPECIFIED",
		1: "ALERT_TYPE_PRICE_ABOVE",
		2: "ALERT_TYPE_PRICE_BELOW",
		3: "ALERT_TYPE_VOLUME_SPIKE",
		4: "ALERT_TYPE_KEYWORD",
		5: "ALERT_TYPE_FEED_DOWN",
	}
	AlertType_value = map[string]int32{
		"ALERT_TYPE_UNSPECIFIED":  0,
		"ALERT_TYPE_PRICE_ABOVE":  1,
		"ALERT_TYPE_PRICE_BELOW":  2,
		"ALERT_TYPE_VOLUME_SPIKE": 3,
		"ALERT_TYPE_KEYWORD":      4,
		"ALERT_TYPE_FEED_DOWN":    5,
	}
)

func (x AlertType) Enum() *AlertType {
	p := new(AlertType)
	*p = x
	return p
}

func (x AlertType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AlertType) Descriptor() protoreflect.EnumDescriptor {
	return file_notbbg_v1_types_proto_enumTypes[1].Descriptor()
}

func (AlertType) Type() protoreflect.EnumType {
	return &file_notbbg_v1_types_proto_enumTypes[1]
}

func (x AlertType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AlertType.Descriptor instead.
func (AlertType) EnumDescriptor() ([]byte, []int) {
	return file_notbbg_v1_types_proto_rawDescGZIP(), []int{1}
}

type AlertStatus int32

const (
	AlertStatus_ALERT_STATUS_UNSPECIFIED AlertStatus = 0
	AlertStatus_ALERT_STATUS_ACTIVE      AlertStatus = 1
	AlertStatus_ALERT_STATUS_TRIGGERED   AlertStatus = 2
	AlertStatus_ALERT_STATUS_DISMISSED   AlertStatus = 3
)

// Enum value maps for AlertStatus.
var (
	AlertStatus_name = map[int32]string{
		0: "ALERT_STATUS_UNSPECIFIED",
		1: "ALERT_STATUS_ACTIVE",
		2: "ALERT_STATUS_TRIGGERED",
		3: "ALERT_STATUS_DISMISSED",
	}
	AlertStatus_value = map[string]int32{
		"ALERT_STATUS_UNSPECIFIED": 0,
		"ALERT_STATUS_ACTIVE":      1,
		"ALERT_STATUS_TRIGGERED":   2,
		"ALERT_STATUS_DISMISSED":   3,
	}
)

func (x AlertStatus) Enum() *AlertStatus {
	p := new(AlertStatus)
	*p = x
	return p
}

func (x AlertStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AlertStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_notbbg_v1_types_proto_enumTypes[2].Descriptor()
}

func (AlertStatus) Type() protoreflect.EnumType {
	return &file_notbbg_v1_types_proto_enumTypes[2]
}

func (x AlertStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AlertStatus.Descriptor instead.
func (AlertStatus) EnumDescriptor() ([]byte, []int) {
	return file_notbbg_v1_types_proto_rawDescGZIP(), []int{2}
}

type FeedState int32

const (
	FeedState_FEED_STATE_UNSPECIFIED  FeedState = 0
	FeedState_FEED_STATE_CONNECTED    FeedState = 1
	FeedState_FEED_STATE_RECONNECTING FeedState = 2
	FeedState_FEED_STATE_STALE        FeedState = 3
	FeedState_FEED_STATE_ERROR        FeedState = 4
)

// Enum value maps for FeedState.
var (
	FeedState_name = map[int32]string{
		0: "FEED_STATE_UNSPECIFIED",
		1: "FEED_STATE_CONNECTED",
		2: "FEED_STATE_RECONNECTING",
		3: "FEED_STATE_STALE",
		4: "FEED_STATE_ERROR",
	}
	FeedState_value = map[string]int32{
		"FEED_STATE_UNSPECIFIED":  0,
		"FEED_STATE_CONNECTED":    1,
		"FEED_STATE_RECONNECTING": 2,
		"FEED_STATE_STALE":        3,
		"FEED_STATE_ERROR":        4,
	}
)

func (x FeedState) Enum() *FeedState {
	p := new(FeedState)
	*p = x
	return p
}

func (x FeedState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FeedState) Descriptor() protoreflect.EnumDescriptor {
	return file_notbbg_v1_types_proto_enumTypes[3].Descriptor()
}

func (FeedState) Type() protoreflect.EnumType {
	return &file_notbbg_v1_types_proto_enumTypes[3]
}

func (x FeedState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FeedState.Descriptor instead.
func (FeedState) EnumDescriptor() ([]byte, []int) {
	return file_notbbg_v1_types_proto_rawDescGZIP(), []int{3}
}

// Canonical OHLC candlestick data.
//
// double fields keep the fast-math path (charts, indicators).
// _decimal counterparts carry the exchange-committed string —
// REQUIRED for crypto where adapter rounding can drift cents
// (decision 2026-04-24, captured in feedback_decimal_required.md).
// Adapters populate decimals from the raw json.Number; consumers
// needing exact fidelity (backtester, audit, OMS) prefer them.
type OHLC struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Instrument    string                 `protobuf:"bytes,1,opt,name=instrument,proto3" json:"instrument,omitempty"` // e.g. "BTCUSD"
	Exchange      string                 `protobuf:"bytes,2,opt,name=exchange,proto3" json:"exchange,omitempty"`     // e.g. "binance"
	Timeframe     string                 `protobuf:"bytes,3,opt,name=timeframe,proto3" json:"timeframe,omitempty"`   // e.g. "1m", "5m", "1h", "1d"
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Open          float64                `protobuf:"fixed64,5,opt,name=open,proto3" json:"open,omitempty"`
	High          float64                `protobuf:"fixed64,6,opt,name=high,proto3" json:"high,omitempty"`
	Low           float64                `protobuf:"fixed64,7,opt,name=low,proto3" json:"low,omitempty"`
	Close         float64                `protobuf:"fixed64,8,opt,name=close,proto3" json:"close,omitempty"`
	Volume        float64                `protobuf:"fixed64,9,opt,name=volume,proto3" json:"volume,omitempty"`
	OpenDecimal   string                 `protobuf:"bytes,10,opt,name=open_decimal,json=openDecimal,proto3" json:"open_decimal,omitempty"`
	HighDecimal   string                 `protobuf:"bytes,11,opt,name=high_decimal,json=highDecimal,proto3" json:"high_decimal,omitempty"`
	LowDecimal    string                 `protobuf:"bytes,12,opt,name=low_decimal,json=lowDecimal,proto3" json:"low_decimal,omitempty"`
	CloseDecimal  string                 `protobuf:"bytes,13,opt,name=close_decimal,json=closeDecimal,proto3" json:"close_decimal,omitempty"`
	VolumeDecimal string                 `protobuf:"bytes,14,opt,name=volume_decimal,json=volumeDecimal,proto3" json:"volume_decimal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OHLC) Reset() {
	*x = OHLC{}
	mi := &file_notbbg_v1_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OHLC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OHLC) ProtoMessage() {}

func (x *OHLC) ProtoReflect() protoreflect.Message {
	mi := &file_notbbg_v1_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OHLC.ProtoReflect.Descriptor instead.
func (*OHLC) Descriptor() ([]byte, []int) {
	return file_notbbg_v1_types_proto_rawDescGZIP(), []int{0}
}

func (x *OHLC) GetInstrument() string {
	if x != nil {
		return x.Instrument
	}
	return ""
}

func (x *OHLC) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

func (x *OHLC) GetTimeframe() string {
	if x != nil {
		return x.Timeframe
	}
	return ""
}

func (x *OHLC) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *OHLC) GetOpen() float64 {
	if x != nil {
		return x.Open
	}
	return 0
}

func (x *OHLC) GetHigh() float64 {
	if x != nil {
		return x.High
	}
	return 0
}

func (x *OHLC) GetLow() float64 {
	if x != nil {
		return x.Low
	}
	return 0
}

func (x *OHLC) GetClose() float64 {
	if x != nil {
		return x.Close
	}
	return 0
}

func (x *OHLC) GetVolume() float64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *OHLC) GetOpenDecimal() string {
	if x != nil {
		return x.OpenDecimal
	}
	return ""
}

func (x *OHLC) GetHighDecimal() string {
	if x != nil {
		return x.HighDecimal
	}
	return ""
}

func (x *OHLC) GetLowDecimal() string {
	if x != nil {
		return x.LowDecimal
	}
	return ""
}

func (x *OHLC) GetCloseDecimal() string {
	if x != nil {
		return x.CloseDecimal
	}
	return ""
}

func (x *OHLC) GetVolumeDecimal() string {
	if x != nil {
		return x.VolumeDecimal
	}
	return ""
}

// Single price level in an order book.
type PriceLevel struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Price           float64                `protobuf:"fixed64,1,opt,name=price,proto3" json:"price,omitempty"`
	Quantity        float64                `protobuf:"fixed64,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	OrderCount      uint32                 `protobuf:"varint,3,opt,name=order_count,json=orderCount,proto3" json:"order_count,omitempty"`      // populated where venue exposes (e.g. Bybit); zero otherwise
	PriceDecimal    string                 `protobuf:"bytes,4,opt,name=price_decimal,json=priceDecimal,proto3" json:"price_decimal,omitempty"` // exchange-committed string (see OHLC above)
	QuantityDecimal string                 `protobuf:"bytes,5,opt,name=quantity_decimal,json=quantityDecimal,proto3" json:"quantity_decimal,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PriceLevel) Reset() {
	*x = PriceLevel{}
	mi := &file_notbbg_v1_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PriceLevel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriceLevel) ProtoMessage() {}

func (x *PriceLevel) ProtoReflect() protoreflect.Message {
	mi := &file_notbbg_v1_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriceLevel.ProtoReflect.Descriptor instead.
func (*PriceLevel) Descriptor() ([]byte, []int) {
	return file_notbbg_v1_types_proto_rawDescGZIP(), []int{1}
}

func (x *PriceLevel) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *PriceLevel) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *PriceLevel) GetOrderCount() uint32 {
	if x != nil {
		return x.OrderCount
	}
	return 0
}

func (x *PriceLevel) GetPriceDecimal() string {
	if x != nil {
		return x.PriceDecimal
	}
	return ""
}

func (x *PriceLevel) GetQuantityDecimal() string {
	if x != nil {
		return x.QuantityDecimal
	}
	return ""
}

// Snapshot of a limit order book.
type LOBSnapshot struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Instrument     string                 `protobuf:"bytes,1,opt,name=instrument,proto3" json:"instrument,omitempty"`
	Exchange       string                 `protobuf:"bytes,2,opt,name=exchange,proto3" json:"exchange,omitempty"`
	Timestamp      *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	SequenceNumber uint64                 `protobuf:"varint,4,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	Bids           []*PriceLevel          `protobuf:"bytes,5,rep,name=bids,proto3" json:"bids,omitempty"`
	Asks           []*PriceLevel          `protobuf:"bytes,6,rep,name=asks,proto3" json:"asks,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LOBSnapshot) Reset() {
	*x = LOBSnapshot{}
	mi := &file_notbbg_v1_types_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LOBSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LOBSnapshot) ProtoMessage() {}

func (x *LOBSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_notbbg_v1_types_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LOBSnapshot.ProtoReflect.Descriptor instead.
func (*LOBSnapshot) Descriptor() ([]byte, []int) {
	return file_notbbg_v1_types_proto_rawDescGZIP(), []int{2}
}

func (x *LOBSnapshot) GetInstrument() string {
	if x != nil {
		return x.Instrument
	}
	return ""
}

func (x *LOBSnapshot) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

func (x *LOBSnapshot) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *LOBSnapshot) GetSequenceNumber() uint64 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

func (x *LOBSnapshot) GetBids() []*PriceLevel {
	if x != nil {
		return x.Bids
	}
	return nil
}

func (x *LOBSnapshot) GetAsks() []*PriceLevel {
	if x != nil {
		return x.Asks
	}
	return nil
}

// A single executed trade.
type Trade struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Instrument      string                 `protobuf:"bytes,1,opt,name=instrument,proto3" json:"instrument,omitempty"`
	Exchange        string                 `protobuf:"bytes,2,opt,name=exchange,proto3" json:"exchange,omitempty"`
	Timestamp       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Price           float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	Quantity        float64                `protobuf:"fixed64,5,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Side            Side                   `protobuf:"varint,6,opt,name=side,proto3,enum=notbbg.v1.Side" json:"side,omitempty"`
	TradeId         string                 `protobuf:"bytes,7,opt,name=trade_id,json=tradeId,proto3" json:"trade_id,omitempty"`
	PriceDecimal    string                 `protobuf:"bytes,8,opt,name=price_decimal,json=priceDecimal,proto3" json:"price_decimal,omitempty"` // exchange-committed string (see OHLC above)
	QuantityDecimal string                 `protobuf:"bytes,9,opt,name=quantity_decimal,json=quantityDecimal,proto3" json:"quantity_decimal,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Trade) Reset() {
	*x = Trade{}
	mi := &file_notbbg_v1_types_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Trade) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Trade) ProtoMessage() {}

func (x *Trade) ProtoReflect() protoreflect.Message {
	mi := &file_notbbg_v1_types_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Trade.ProtoReflect.Descriptor instead.
func (*Trade) Descriptor() ([]byte, []int) {
	return file_notbbg_v1_types_proto_rawDescGZIP(), []int{3}
}

func (x *Trade) GetInstrument() string {
	if x != nil {
		return x.Instrument
	}
	return ""
}

func (x *Trade) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

func (x *Trade) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Trade) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Trade) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *Trade) GetSide() Side {
	if x != nil {
		return x.Side
	}
	return Side_SIDE_UNSPECIFIED
}

func (x *Trade) GetTradeId() string {
	if x != nil {
		return x.TradeId
	}
	return ""
}

func (x *Trade) GetPriceDecimal() string {
	if x != nil {
		return x.PriceDecimal
	}
	return ""
}

func (x *Trade) GetQuantityDecimal() string {
	if x != nil {
		return x.QuantityDecimal
	}
	return ""
}

// A news item from RSS, GDELT, or other sources.
type NewsItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Body          string                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	Source        string                 `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"` // e.g. "reuters", "coindesk"
	Url           string                 `protobuf:"bytes,5,opt,name=url,proto3" json:"url,omitempty"`
	PublishedAt   *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=published_at,json=publishedAt,proto3" json:"published_at,omitempty"`
	Tickers       []string               `protobuf:"bytes,7,rep,name=tickers,proto3" json:"tickers,omitempty"` // related tickers
	Keywords      []string               `protobuf:"bytes,8,rep,name=keywords,proto3" json:"keywords,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewsItem) Reset() {
	*x = NewsItem{}
	mi := &file_notbbg_v1_types_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewsItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewsItem) ProtoMessage() {}

func (x *NewsItem) ProtoReflect() protoreflect.Message {
	mi := &file_notbbg_v1_types_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewsItem.ProtoReflect.Descriptor instead.
func (*NewsItem) Descriptor() ([]byte, []int) {
	return file_notbbg_v1_types_proto_rawDescGZIP(), []int{4}
}

func (x *NewsItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NewsItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *NewsItem) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *NewsItem) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *NewsItem) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *NewsItem) GetPublishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PublishedAt
	}
	return nil
}

func (x *NewsItem) GetTickers() []string {
	if x != nil {
		return x.Tickers
	}
	return nil
}

func (x *NewsItem) GetKeywords() []string {
	if x != nil {
		return x.Keywords
	}
	return nil
}

// An alert definition or triggered alert.
type Alert struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          AlertType              `protobuf:"varint,2,opt,name=type,proto3,enum=notbbg.v1.AlertType" json:"type,omitempty"`
	Instrument    string                 `protobuf:"bytes,3,opt,name=instrument,proto3" json:"instrument,omitempty"` // empty for keyword/feed alerts
	Condition     string                 `protobuf:"bytes,4,opt,name=condition,proto3" json:"condition,omitempty"`   // human-readable condition, e.g. "> 100000"
	Threshold     float64                `protobuf:"fixed64,5,opt,name=threshold,proto3" json:"threshold,omitempty"`
	Status        AlertStatus            `protobuf:"varint,6,opt,name=status,proto3,enum=notbbg.v1.AlertStatus" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	TriggeredAt   *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=triggered_at,json=triggeredAt,proto3" json:"triggered_at,omitempty"`
	Payload       string                 `protobuf:"bytes,9,opt,name=payload,proto3" json:"payload,omitempty"` // additional context when triggered
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Alert) Reset() {
	*x = Alert{}
	mi := &file_notbbg_v1_types_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Alert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Alert) ProtoMessage() {}

func (x *Alert) ProtoReflect() protoreflect.Message {
	mi := &file_notbbg_v1_types_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Alert.ProtoReflect.Descriptor instead.
func (*Alert) Descriptor() ([]byte, []int) {
	return file_notbbg_v1_types_proto_rawDescGZIP(), []int{5}
}

func (x *Alert) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Alert) GetType() AlertType {
	if x != nil {
		return x.Type
	}
	return AlertType_ALERT_TYPE_UNSPECIFIED
}

func (x *Alert) GetInstrument() string {
	if x != nil {
		return x.Instrument
	}
	return ""
}

func (x *Alert) GetCondition() string {
	if x != nil {
		return x.Condition
	}
	return ""
}

func (x *Alert) GetThreshold() float64 {
	if x != nil {
		return x.Threshold
	}
	return 0
}

func (x *Alert) GetStatus() AlertStatus {
	if x != nil {
		return x.Status
	}
	return AlertStatus_ALERT_STATUS_UNSPECIFIED
}

func (x *Alert) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Alert) GetTriggeredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.TriggeredAt
	}
	return nil
}

func (x *Alert) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

// Health status of a data feed.
type FeedStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceName    string                 `protobuf:"bytes,1,opt,name=source_name,json=sourceName,proto3" json:"source_name,omitempty"`
	LastUpdate    *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=last_update,json=lastUpdate,proto3" json:"last_update,omitempty"`
	LatencyP50Ms  float64                `protobuf:"fixed64,3,opt,name=latency_p50_ms,json=latencyP50Ms,proto3" json:"latency_p50_ms,omitempty"`
	LatencyP95Ms  float64                `protobuf:"fixed64,4,opt,name=latency_p95_ms,json=latencyP95Ms,proto3" json:"latency_p95_ms,omitempty"`
	LatencyP99Ms  float64                `protobuf:"fixed64,5,opt,name=latency_p99_ms,json=latencyP99Ms,proto3" json:"latency_p99_ms,omitempty"`
	ErrorCount    uint64                 `protobuf:"varint,6,opt,name=error_count,json=errorCount,proto3" json:"error_count,omitempty"`
	BytesReceived uint64                 `protobuf:"varint,7,opt,name=bytes_received,json=bytesReceived,proto3" json:"bytes_received,omitempty"`
	State         FeedState              `protobuf:"varint,8,opt,name=state,proto3,enum=notbbg.v1.FeedState" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeedStatus) Reset() {
	*x = FeedStatus{}
	mi := &file_notbbg_v1_types_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeedStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedStatus) ProtoMessage() {}

func (x *FeedStatus) ProtoReflect() protoreflect.Message {
	mi := &file_notbbg_v1_types_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedStatus.ProtoReflect.Descriptor instead.
func (*FeedStatus) Descriptor() ([]byte, []int) {
	return file_notbbg_v1_types_proto_rawDescGZIP(), []int{6}
}

func (x *FeedStatus) GetSourceName() string {
	if x != nil {
		return x.SourceName
	}
	return ""
}

func (x *FeedStatus) GetLastUpdate() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUpdate
	}
	return nil
}

func (x *FeedStatus) GetLatencyP50Ms() float64 {
	if x != nil {
		return x.LatencyP50Ms
	}
	return 0
}

func (x *FeedStatus) GetLatencyP95Ms() float64 {
	if x != nil {
		return x.LatencyP95Ms
	}
	return 0
}

func (x *FeedStatus) GetLatencyP99Ms() float64 {
	if x != nil {
		return x.LatencyP99Ms
	}
	return 0
}

func (x *FeedStatus) GetErrorCount() uint64 {
	if x != nil {
		return x.ErrorCount
	}
	return 0
}

func (x *FeedStatus) GetBytesReceived() uint64 {
	if x != nil {
		return x.BytesReceived
	}
	return 0
}

func (x *FeedStatus) GetState() FeedState {
	if x != nil {
		return x.State
	}
	return FeedState_FEED_STATE_UNSPECIFIED
}

// A topic subscription request from a client.
type Subscription struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"` // glob pattern, e.g. "ohlc.binance.*"
	Filters       map[string]string      `protobuf:"bytes,2,rep,name=filters,proto3" json:"filters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Subscription) Reset() {
	*x = Subscription{}
	mi := &file_notbbg_v1_types_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subscription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subscription) ProtoMessage() {}

func (x *Subscription) ProtoReflect() protoreflect.Message {
	mi := &file_notbbg_v1_types_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subscription.ProtoReflect.Descriptor instead.
func (*Subscription) Descriptor() ([]byte, []int) {
	return file_notbbg_v1_types_proto_rawDescGZIP(), []int{7}
}

func (x *Subscription) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *Subscription) GetFilters() map[string]string {
	if x != nil {
		return x.Filters
	}
	return nil
}

// SeriesKey identifies a point in a multi-dimensional time series.
// The `dims` map holds arbitrary key/value dimensions; well-known
// keys are { type, asset, pair, source, exchange, instrument, tenor,
// strike, side } by convention, but any dim may be added without
// breaking compatibility. See DATA-PLAN.md §5.
type SeriesKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dims          map[string]string      `protobuf:"bytes,1,rep,name=dims,proto3" json:"dims,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SeriesKey) Reset() {
	*x = SeriesKey{}
	mi := &file_notbbg_v1_types_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeriesKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeriesKey) ProtoMessage() {}

func (x *SeriesKey) ProtoReflect() protoreflect.Message {
	mi := &file_notbbg_v1_types_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeriesKey.ProtoReflect.Descriptor instead.
func (*SeriesKey) Descriptor() ([]byte, []int) {
	return file_notbbg_v1_types_proto_rawDescGZIP(), []int{8}
}

func (x *SeriesKey) GetDims() map[string]string {
	if x != nil {
		return x.Dims
	}
	return nil
}

// SeriesPoint is a single timestamped observation for a SeriesKey.
// The value is an oneof so scalars, structured market data, or
// arbitrary raw bytes can all be carried.
type SeriesPoint struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Key   *SeriesKey             `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	T     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=t,proto3" json:"t,omitempty"`
	// Types that are valid to be assigned to Value:
	//
	//	*SeriesPoint_Scalar
	//	*SeriesPoint_Ohlc
	//	*SeriesPoint_Lob
	//	*SeriesPoint_Trade
	//	*SeriesPoint_Raw
	Value         isSeriesPoint_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SeriesPoint) Reset() {
	*x = SeriesPoint{}
	mi := &file_notbbg_v1_types_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeriesPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeriesPoint) ProtoMessage() {}

func (x *SeriesPoint) ProtoReflect() protoreflect.Message {
	mi := &file_notbbg_v1_types_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeriesPoint.ProtoReflect.Descriptor instead.
func (*SeriesPoint) Descriptor() ([]byte, []int) {
	return file_notbbg_v1_types_proto_rawDescGZIP(), []int{9}
}

func (x *SeriesPoint) GetKey() *SeriesKey {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *SeriesPoint) GetT() *timestamppb.Timestamp {
	if x != nil {
		return x.T
	}
	return nil
}

func (x *SeriesPoint) GetValue() isSeriesPoint_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *SeriesPoint) GetScalar() float64 {
	if x != nil {
		if x, ok := x.Value.(*SeriesPoint_Scalar); ok {
			return x.Scalar
		}
	}
	return 0
}

func (x *SeriesPoint) GetOhlc() *OHLC {
	if x != nil {
		if x, ok := x.Value.(*SeriesPoint_Ohlc); ok {
			return x.Ohlc
		}
	}
	return nil
}

func (x *SeriesPoint) GetLob() *LOBSnapshot {
	if x != nil {
		if x, ok := x.Value.(*SeriesPoint_Lob); ok {
			return x.Lob
		}
	}
	return nil
}

func (x *SeriesPoint) GetTrade() *Trade {
	if x != nil {
		if x, ok := x.Value.(*SeriesPoint_Trade); ok {
			return x.Trade
		}
	}
	return nil
}

func (x *SeriesPoint) GetRaw() []byte {
	if x != nil {
		if x, ok := x.Value.(*SeriesPoint_Raw); ok {
			return x.Raw
		}
	}
	return nil
}

type isSeriesPoint_Value interface {
	isSeriesPoint_Value()
}

type SeriesPoint_Scalar struct {
	Scalar float64 `protobuf:"fixed64,10,opt,name=scalar,proto3,oneof"`
}

type SeriesPoint_Ohlc struct {
	Ohlc *OHLC `protobuf:"bytes,11,opt,name=ohlc,proto3,oneof"`
}

type SeriesPoint_Lob struct {
	Lob *LOBSnapshot `protobuf:"bytes,12,opt,name=lob,proto3,oneof"`
}

type SeriesPoint_Trade struct {
	Trade *Trade `protobuf:"bytes,13,opt,name=trade,proto3,oneof"`
}

type SeriesPoint_Raw struct {
	Raw []byte `protobuf:"bytes,14,opt,name=raw,proto3,oneof"`
}

func (*SeriesPoint_Scalar) isSeriesPoint_Value() {}

func (*SeriesPoint_Ohlc) isSeriesPoint_Value() {}

func (*SeriesPoint_Lob) isSeriesPoint_Value() {}

func (*SeriesPoint_Trade) isSeriesPoint_Value() {}

func (*SeriesPoint_Raw) isSeriesPoint_Value() {}

// Wrapper for any message sent over the bus or wire.
type Update struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Topic     string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Update_Ohlc
	//	*Update_Lob
	//	*Update_Trade
	//	*Update_News
	//	*Update_Alert
	//	*Update_FeedStatus
	Payload       isUpdate_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Update) Reset() {
	*x = Update{}
	mi := &file_notbbg_v1_types_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Update) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Update) ProtoMessage() {}

func (x *Update) ProtoReflect() protoreflect.Message {
	mi := &file_notbbg_v1_types_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Update.ProtoReflect.Descriptor instead.
func (*Update) Descriptor() ([]byte, []int) {
	return file_notbbg_v1_types_proto_rawDescGZIP(), []int{10}
}

func (x *Update) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *Update) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Update) GetPayload() isUpdate_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Update) GetOhlc() *OHLC {
	if x != nil {
		if x, ok := x.Payload.(*Update_Ohlc); ok {
			return x.Ohlc
		}
	}
	return nil
}

func (x *Update) GetLob() *LOBSnapshot {
	if x != nil {
		if x, ok := x.Payload.(*Update_Lob); ok {
			return x.Lob
		}
	}
	return nil
}

func (x *Update) GetTrade() *Trade {
	if x != nil {
		if x, ok := x.Payload.(*Update_Trade); ok {
			return x.Trade
		}
	}
	return nil
}

func (x *Update) GetNews() *NewsItem {
	if x != nil {
		if x, ok := x.Payload.(*Update_News); ok {
			return x.News
		}
	}
	return nil
}

func (x *Update) GetAlert() *Alert {
	if x != nil {
		if x, ok := x.Payload.(*Update_Alert); ok {
			return x.Alert
		}
	}
	return nil
}

func (x *Update) GetFeedStatus() *FeedStatus {
	if x != nil {
		if x, ok := x.Payload.(*Update_FeedStatus); ok {
			return x.FeedStatus
		}
	}
	return nil
}

type isUpdate_Payload interface {
	isUpdate_Payload()
}

type Update_Ohlc struct {
	Ohlc *OHLC `protobuf:"bytes,10,opt,name=ohlc,proto3,oneof"`
}

type Update_Lob struct {
	Lob *LOBSnapshot `protobuf:"bytes,11,opt,name=lob,proto3,oneof"`
}

type Update_Trade struct {
	Trade *Trade `protobuf:"bytes,12,opt,name=trade,proto3,oneof"`
}

type Update_News struct {
	News *NewsItem `protobuf:"bytes,13,opt,name=news,proto3,oneof"`
}

type Update_Alert struct {
	Alert *Alert `protobuf:"bytes,14,opt,name=alert,proto3,oneof"`
}

type Update_FeedStatus struct {
	FeedStatus *FeedStatus `protobuf:"bytes,15,opt,name=feed_status,json=feedStatus,proto3,oneof"`
}

func (*Update_Ohlc) isUpdate_Payload() {}

func (*Update_Lob) isUpdate_Payload() {}

func (*Update_Trade) isUpdate_Payload() {}

func (*Update_News) isUpdate_Payload() {}

func (*Update_Alert) isUpdate_Payload() {}

func (*Update_FeedStatus) isUpdate_Payload() {}

// Aggregated trade activity over a window. Replaces the ad-hoc
// map[string]any payload TUI/desktop saw on `trade.agg.<exchange>.<symbol>`.
type TradeAgg struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Instrument  string                 `protobuf:"bytes,1,opt,name=instrument,proto3" json:"instrument,omitempty"`
	Exchange    string                 `protobuf:"bytes,2,opt,name=exchange,proto3" json:"exchange,omitempty"`
	WindowStart *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=window_start,json=windowStart,proto3" json:"window_start,omitempty"`
	WindowEnd   *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=window_end,json=windowEnd,proto3" json:"window_end,omitempty"`
	Count       uint64                 `protobuf:"varint,5,opt,name=count,proto3" json:"count,omitempty"`        // number of trades in the window
	Volume      float64                `protobuf:"fixed64,6,opt,name=volume,proto3" json:"volume,omitempty"`     // sum of quantities
	Notional    float64                `protobuf:"fixed64,7,opt,name=notional,proto3" json:"notional,omitempty"` // sum of (price * quantity)
	Vwap        float64                `protobuf:"fixed64,8,opt,name=vwap,proto3" json:"vwap,omitempty"`         // notional / volume (when volume > 0)
	BuyCount    uint64                 `protobuf:"varint,9,opt,name=buy_count,json=buyCount,proto3" json:"buy_count,omitempty"`
	SellCount   uint64                 `protobuf:"varint,10,opt,name=sell_count,json=sellCount,proto3" json:"sell_count,omitempty"`
	// Side bias in [-1, 1]; positive = more buy-side notional.
	SideBias      float64 `protobuf:"fixed64,11,opt,name=side_bias,json=sideBias,proto3" json:"side_bias,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TradeAgg) Reset() {
	*x = TradeAgg{}
	mi := &file_notbbg_v1_types_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TradeAgg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TradeAgg) ProtoMessage() {}

func (x *TradeAgg) ProtoReflect() protoreflect.Message {
	mi := &file_notbbg_v1_types_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TradeAgg.ProtoReflect.Descriptor instead.
func (*TradeAgg) Descriptor() ([]byte, []int) {
	return file_notbbg_v1_types_proto_rawDescGZIP(), []int{11}
}

func (x *TradeAgg) GetInstrument() string {
	if x != nil {
		return x.Instrument
	}
	return ""
}

func (x *TradeAgg) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

func (x *TradeAgg) GetWindowStart() *timestamppb.Timestamp {
	if x != nil {
		return x.WindowStart
	}
	return nil
}

func (x *TradeAgg) GetWindowEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.WindowEnd
	}
	return nil
}

func (x *TradeAgg) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *TradeAgg) GetVolume() float64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *TradeAgg) GetNotional() float64 {
	if x != nil {
		return x.Notional
	}
	return 0
}

func (x *TradeAgg) GetVwap() float64 {
	if x != nil {
		return x.Vwap
	}
	return 0
}

func (x *TradeAgg) GetBuyCount() uint64 {
	if x != nil {
		return x.BuyCount
	}
	return 0
}

func (x *TradeAgg) GetSellCount() uint64 {
	if x != nil {
		return x.SellCount
	}
	return 0
}

func (x *TradeAgg) GetSideBias() float64 {
	if x != nil {
		return x.SideBias
	}
	return 0
}

// One-shot snapshot of the most recent trades for a topic; used for
// late-joining-client warmup so the trades panel isn't empty until
// the next live trade arrives.
type TradeSnap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Instrument    string                 `protobuf:"bytes,1,opt,name=instrument,proto3" json:"instrument,omitempty"`
	Exchange      string                 `protobuf:"bytes,2,opt,name=exchange,proto3" json:"exchange,omitempty"`
	GeneratedAt   *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=generated_at,json=generatedAt,proto3" json:"generated_at,omitempty"`
	Trades        []*Trade               `protobuf:"bytes,4,rep,name=trades,proto3" json:"trades,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TradeSnap) Reset() {
	*x = TradeSnap{}
	mi := &file_notbbg_v1_types_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TradeSnap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TradeSnap) ProtoMessage() {}

func (x *TradeSnap) ProtoReflect() protoreflect.Message {
	mi := &file_notbbg_v1_types_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TradeSnap.ProtoReflect.Descriptor instead.
func (*TradeSnap) Descriptor() ([]byte, []int) {
	return file_notbbg_v1_types_proto_rawDescGZIP(), []int{12}
}

func (x *TradeSnap) GetInstrument() string {
	if x != nil {
		return x.Instrument
	}
	return ""
}

func (x *TradeSnap) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

func (x *TradeSnap) GetGeneratedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.GeneratedAt
	}
	return nil
}

func (x *TradeSnap) GetTrades() []*Trade {
	if x != nil {
		return x.Trades
	}
	return nil
}

// Single row of the cross-venue price-sanity matrix. Replaces the
// per-row map[string]any the SANITY tab consumes.
type SanityRow struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Pair        string                 `protobuf:"bytes,1,opt,name=pair,proto3" json:"pair,omitempty"` // e.g. "BTCUSDT"
	MedianPrice float64                `protobuf:"fixed64,2,opt,name=median_price,json=medianPrice,proto3" json:"median_price,omitempty"`
	MaxDevBp    float64                `protobuf:"fixed64,3,opt,name=max_dev_bp,json=maxDevBp,proto3" json:"max_dev_bp,omitempty"` // max venue deviation in basis points
	UpdatedAt   *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// Per-venue breakdown: { exchange -> price }.
	Prices        map[string]float64 `protobuf:"bytes,5,rep,name=prices,proto3" json:"prices,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SanityRow) Reset() {
	*x = SanityRow{}
	mi := &file_notbbg_v1_types_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SanityRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SanityRow) ProtoMessage() {}

func (x *SanityRow) ProtoReflect() protoreflect.Message {
	mi := &file_notbbg_v1_types_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SanityRow.ProtoReflect.Descriptor instead.
func (*SanityRow) Descriptor() ([]byte, []int) {
	return file_notbbg_v1_types_proto_rawDescGZIP(), []int{13}
}

func (x *SanityRow) GetPair() string {
	if x != nil {
		return x.Pair
	}
	return ""
}

func (x *SanityRow) GetMedianPrice() float64 {
	if x != nil {
		return x.MedianPrice
	}
	return 0
}

func (x *SanityRow) GetMaxDevBp() float64 {
	if x != nil {
		return x.MaxDevBp
	}
	return 0
}

func (x *SanityRow) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *SanityRow) GetPrices() map[string]float64 {
	if x != nil {
		return x.Prices
	}
	return nil
}

// Snapshot of the entire sanity matrix; published on `sanity.prices`
// at a slow cadence (so the SANITY tab can re-render in one frame).
type SanitySnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GeneratedAt   *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=generated_at,json=generatedAt,proto3" json:"generated_at,omitempty"`
	Rows          []*SanityRow           `protobuf:"bytes,2,rep,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SanitySnapshot) Reset() {
	*x = SanitySnapshot{}
	mi := &file_notbbg_v1_types_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SanitySnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SanitySnapshot) ProtoMessage() {}

func (x *SanitySnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_notbbg_v1_types_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SanitySnapshot.ProtoReflect.Descriptor instead.
func (*SanitySnapshot) Descriptor() ([]byte, []int) {
	return file_notbbg_v1_types_proto_rawDescGZIP(), []int{14}
}

func (x *SanitySnapshot) GetGeneratedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.GeneratedAt
	}
	return nil
}

func (x *SanitySnapshot) GetRows() []*SanityRow {
	if x != nil {
		return x.Rows
	}
	return nil
}

// Plugin liveness status. Published on `plugin.status` every ~10 s.
// The Go plugins.computePluginState function emits this shape.
type PluginStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	State         string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"` // "connected" | "stale" | "error" | "stopped"
	LastActivity  *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=last_activity,json=lastActivity,proto3" json:"last_activity,omitempty"`
	Pid           int32                  `protobuf:"varint,4,opt,name=pid,proto3" json:"pid,omitempty"`
	ErrorCount    uint64                 `protobuf:"varint,5,opt,name=error_count,json=errorCount,proto3" json:"error_count,omitempty"`
	Running       bool                   `protobuf:"varint,6,opt,name=running,proto3" json:"running,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginStatus) Reset() {
	*x = PluginStatus{}
	mi := &file_notbbg_v1_types_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginStatus) ProtoMessage() {}

func (x *PluginStatus) ProtoReflect() protoreflect.Message {
	mi := &file_notbbg_v1_types_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginStatus.ProtoReflect.Descriptor instead.
func (*PluginStatus) Descriptor() ([]byte, []int) {
	return file_notbbg_v1_types_proto_rawDescGZIP(), []int{15}
}

func (x *PluginStatus) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PluginStatus) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *PluginStatus) GetLastActivity() *timestamppb.Timestamp {
	if x != nil {
		return x.LastActivity
	}
	return nil
}

func (x *PluginStatus) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *PluginStatus) GetErrorCount() uint64 {
	if x != nil {
		return x.ErrorCount
	}
	return 0
}

func (x *PluginStatus) GetRunning() bool {
	if x != nil {
		return x.Running
	}
	return false
}

// GenericRow carries free-form rows from sources whose schema isn't
// stable enough to bind to a strongly-typed proto today (Sibelius
// tsbase_files, Ravel adapter, ad-hoc CSV ingest). The `payload`
// field uses google.protobuf.Struct so existing JSON-blob-style
// publishers don't have to upgrade in lockstep with the U1 work.
//
// New publishers SHOULD prefer a proper proto. GenericRow is the
// escape hatch, not the recommendation.
type GenericRow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"` // e.g. "sibelius", "ravel", "tsbase_files"
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`     // source-defined row kind, e.g. "voltools.snap"
	ObservedAt    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=observed_at,json=observedAt,proto3" json:"observed_at,omitempty"`
	Payload       *structpb.Struct       `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenericRow) Reset() {
	*x = GenericRow{}
	mi := &file_notbbg_v1_types_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenericRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenericRow) ProtoMessage() {}

func (x *GenericRow) ProtoReflect() protoreflect.Message {
	mi := &file_notbbg_v1_types_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenericRow.ProtoReflect.Descriptor instead.
func (*GenericRow) Descriptor() ([]byte, []int) {
	return file_notbbg_v1_types_proto_rawDescGZIP(), []int{16}
}

func (x *GenericRow) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *GenericRow) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *GenericRow) GetObservedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ObservedAt
	}
	return nil
}

func (x *GenericRow) GetPayload() *structpb.Struct {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_notbbg_v1_types_proto protoreflect.FileDescriptor

const file_notbbg_v1_types_proto_rawDesc = "" +
	"\n" +
	"\x15notbbg/v1/types.proto\x12\tnotbbg.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xb5\x03\n" +
	"\x04OHLC\x12\x1e\n" +
	"\n" +
	"instrument\x18\x01 \x01(\tR\n" +
	"instrument\x12\x1a\n" +
	"\bexchange\x18\x02 \x01(\tR\bexchange\x12\x1c\n" +
	"\ttimeframe\x18\x03 \x01(\tR\ttimeframe\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x12\n" +
	"\x04open\x18\x05 \x01(\x01R\x04open\x12\x12\n" +
	"\x04high\x18\x06 \x01(\x01R\x04high\x12\x10\n" +
	"\x03low\x18\a \x01(\x01R\x03low\x12\x14\n" +
	"\x05close\x18\b \x01(\x01R\x05close\x12\x16\n" +
	"\x06volume\x18\t \x01(\x01R\x06volume\x12!\n" +
	"\fopen_decimal\x18\n" +
	" \x01(\tR\vopenDecimal\x12!\n" +
	"\fhigh_decimal\x18\v \x01(\tR\vhighDecimal\x12\x1f\n" +
	"\vlow_decimal\x18\f \x01(\tR\n" +
	"lowDecimal\x12#\n" +
	"\rclose_decimal\x18\r \x01(\tR\fcloseDecimal\x12%\n" +
	"\x0evolume_decimal\x18\x0e \x01(\tR\rvolumeDecimal\"\xaf\x01\n" +
	"\n" +
	"PriceLevel\x12\x14\n" +
	"\x05price\x18\x01 \x01(\x01R\x05price\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x01R\bquantity\x12\x1f\n" +
	"\vorder_count\x18\x03 \x01(\rR\n" +
	"orderCount\x12#\n" +
	"\rprice_decimal\x18\x04 \x01(\tR\fpriceDecimal\x12)\n" +
	"\x10quantity_decimal\x18\x05 \x01(\tR\x0fquantityDecimal\"\x82\x02\n" +
	"\vLOBSnapshot\x12\x1e\n" +
	"\n" +
	"instrument\x18\x01 \x01(\tR\n" +
	"instrument\x12\x1a\n" +
	"\bexchange\x18\x02 \x01(\tR\bexchange\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12'\n" +
	"\x0fsequence_number\x18\x04 \x01(\x04R\x0esequenceNumber\x12)\n" +
	"\x04bids\x18\x05 \x03(\v2\x15.notbbg.v1.PriceLevelR\x04bids\x12)\n" +
	"\x04asks\x18\x06 \x03(\v2\x15.notbbg.v1.PriceLevelR\x04asks\"\xbf\x02\n" +
	"\x05Trade\x12\x1e\n" +
	"\n" +
	"instrument\x18\x01 \x01(\tR\n" +
	"instrument\x12\x1a\n" +
	"\bexchange\x18\x02 \x01(\tR\bexchange\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\x12\x1a\n" +
	"\bquantity\x18\x05 \x01(\x01R\bquantity\x12#\n" +
	"\x04side\x18\x06 \x01(\x0e2\x0f.notbbg.v1.SideR\x04side\x12\x19\n" +
	"\btrade_id\x18\a \x01(\tR\atradeId\x12#\n" +
	"\rprice_decimal\x18\b \x01(\tR\fpriceDecimal\x12)\n" +
	"\x10quantity_decimal\x18\t \x01(\tR\x0fquantityDecimal\"\xe3\x01\n" +
	"\bNewsItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04body\x18\x03 \x01(\tR\x04body\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\x12\x10\n" +
	"\x03url\x18\x05 \x01(\tR\x03url\x12=\n" +
	"\fpublished_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\vpublishedAt\x12\x18\n" +
	"\atickers\x18\a \x03(\tR\atickers\x12\x1a\n" +
	"\bkeywords\x18\b \x03(\tR\bkeywords\"\xe1\x02\n" +
	"\x05Alert\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12(\n" +
	"\x04type\x18\x02 \x01(\x0e2\x14.notbbg.v1.AlertTypeR\x04type\x12\x1e\n" +
	"\n" +
	"instrument\x18\x03 \x01(\tR\n" +
	"instrument\x12\x1c\n" +
	"\tcondition\x18\x04 \x01(\tR\tcondition\x12\x1c\n" +
	"\tthreshold\x18\x05 \x01(\x01R\tthreshold\x12.\n" +
	"\x06status\x18\x06 \x01(\x0e2\x16.notbbg.v1.AlertStatusR\x06status\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12=\n" +
	"\ftriggered_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\vtriggeredAt\x12\x18\n" +
	"\apayload\x18\t \x01(\tR\apayload\"\xd0\x02\n" +
	"\n" +
	"FeedStatus\x12\x1f\n" +
	"\vsource_name\x18\x01 \x01(\tR\n" +
	"sourceName\x12;\n" +
	"\vlast_update\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastUpdate\x12$\n" +
	"\x0elatency_p50_ms\x18\x03 \x01(\x01R\flatencyP50Ms\x12$\n" +
	"\x0elatency_p95_ms\x18\x04 \x01(\x01R\flatencyP95Ms\x12$\n" +
	"\x0elatency_p99_ms\x18\x05 \x01(\x01R\flatencyP99Ms\x12\x1f\n" +
	"\verror_count\x18\x06 \x01(\x04R\n" +
	"errorCount\x12%\n" +
	"\x0ebytes_received\x18\a \x01(\x04R\rbytesReceived\x12*\n" +
	"\x05state\x18\b \x01(\x0e2\x14.notbbg.v1.FeedStateR\x05state\"\xa0\x01\n" +
	"\fSubscription\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12>\n" +
	"\afilters\x18\x02 \x03(\v2$.notbbg.v1.Subscription.FiltersEntryR\afilters\x1a:\n" +
	"\fFiltersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"x\n" +
	"\tSeriesKey\x122\n" +
	"\x04dims\x18\x01 \x03(\v2\x1e.notbbg.v1.SeriesKey.DimsEntryR\x04dims\x1a7\n" +
	"\tDimsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x93\x02\n" +
	"\vSeriesPoint\x12&\n" +
	"\x03key\x18\x01 \x01(\v2\x14.notbbg.v1.SeriesKeyR\x03key\x12(\n" +
	"\x01t\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x01t\x12\x18\n" +
	"\x06scalar\x18\n" +
	" \x01(\x01H\x00R\x06scalar\x12%\n" +
	"\x04ohlc\x18\v \x01(\v2\x0f.notbbg.v1.OHLCH\x00R\x04ohlc\x12*\n" +
	"\x03lob\x18\f \x01(\v2\x16.notbbg.v1.LOBSnapshotH\x00R\x03lob\x12(\n" +
	"\x05trade\x18\r \x01(\v2\x10.notbbg.v1.TradeH\x00R\x05trade\x12\x12\n" +
	"\x03raw\x18\x0e \x01(\fH\x00R\x03rawB\a\n" +
	"\x05value\"\xef\x02\n" +
	"\x06Update\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12%\n" +
	"\x04ohlc\x18\n" +
	" \x01(\v2\x0f.notbbg.v1.OHLCH\x00R\x04ohlc\x12*\n" +
	"\x03lob\x18\v \x01(\v2\x16.notbbg.v1.LOBSnapshotH\x00R\x03lob\x12(\n" +
	"\x05trade\x18\f \x01(\v2\x10.notbbg.v1.TradeH\x00R\x05trade\x12)\n" +
	"\x04news\x18\r \x01(\v2\x13.notbbg.v1.NewsItemH\x00R\x04news\x12(\n" +
	"\x05alert\x18\x0e \x01(\v2\x10.notbbg.v1.AlertH\x00R\x05alert\x128\n" +
	"\vfeed_status\x18\x0f \x01(\v2\x15.notbbg.v1.FeedStatusH\x00R\n" +
	"feedStatusB\t\n" +
	"\apayload\"\xf7\x02\n" +
	"\bTradeAgg\x12\x1e\n" +
	"\n" +
	"instrument\x18\x01 \x01(\tR\n" +
	"instrument\x12\x1a\n" +
	"\bexchange\x18\x02 \x01(\tR\bexchange\x12=\n" +
	"\fwindow_start\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\vwindowStart\x129\n" +
	"\n" +
	"window_end\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\twindowEnd\x12\x14\n" +
	"\x05count\x18\x05 \x01(\x04R\x05count\x12\x16\n" +
	"\x06volume\x18\x06 \x01(\x01R\x06volume\x12\x1a\n" +
	"\bnotional\x18\a \x01(\x01R\bnotional\x12\x12\n" +
	"\x04vwap\x18\b \x01(\x01R\x04vwap\x12\x1b\n" +
	"\tbuy_count\x18\t \x01(\x04R\bbuyCount\x12\x1d\n" +
	"\n" +
	"sell_count\x18\n" +
	" \x01(\x04R\tsellCount\x12\x1b\n" +
	"\tside_bias\x18\v \x01(\x01R\bsideBias\"\xb0\x01\n" +
	"\tTradeSnap\x12\x1e\n" +
	"\n" +
	"instrument\x18\x01 \x01(\tR\n" +
	"instrument\x12\x1a\n" +
	"\bexchange\x18\x02 \x01(\tR\bexchange\x12=\n" +
	"\fgenerated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\vgeneratedAt\x12(\n" +
	"\x06trades\x18\x04 \x03(\v2\x10.notbbg.v1.TradeR\x06trades\"\x90\x02\n" +
	"\tSanityRow\x12\x12\n" +
	"\x04pair\x18\x01 \x01(\tR\x04pair\x12!\n" +
	"\fmedian_price\x18\x02 \x01(\x01R\vmedianPrice\x12\x1c\n" +
	"\n" +
	"max_dev_bp\x18\x03 \x01(\x01R\bmaxDevBp\x129\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x128\n" +
	"\x06prices\x18\x05 \x03(\v2 .notbbg.v1.SanityRow.PricesEntryR\x06prices\x1a9\n" +
	"\vPricesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"y\n" +
	"\x0eSanitySnapshot\x12=\n" +
	"\fgenerated_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\vgeneratedAt\x12(\n" +
	"\x04rows\x18\x02 \x03(\v2\x14.notbbg.v1.SanityRowR\x04rows\"\xc6\x01\n" +
	"\fPluginStatus\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x12?\n" +
	"\rlast_activity\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\flastActivity\x12\x10\n" +
	"\x03pid\x18\x04 \x01(\x05R\x03pid\x12\x1f\n" +
	"\verror_count\x18\x05 \x01(\x04R\n" +
	"errorCount\x12\x18\n" +
	"\arunning\x18\x06 \x01(\bR\arunning\"\xa8\x01\n" +
	"\n" +
	"GenericRow\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12;\n" +
	"\vobserved_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"observedAt\x121\n" +
	"\apayload\x18\x04 \x01(\v2\x17.google.protobuf.StructR\apayload*9\n" +
	"\x04Side\x12\x14\n" +
	"\x10SIDE_UNSPECIFIED\x10\x00\x12\f\n" +
	"\bSIDE_BUY\x10\x01\x12\r\n" +
	"\tSIDE_SELL\x10\x02*\xae\x01\n" +
	"\tAlertType\x12\x1a\n" +
	"\x16ALERT_TYPE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16ALERT_TYPE_PRICE_ABOVE\x10\x01\x12\x1a\n" +
	"\x16ALERT_TYPE_PRICE_BELOW\x10\x02\x12\x1b\n" +
	"\x17ALERT_TYPE_VOLUME_SPIKE\x10\x03\x12\x16\n" +
	"\x12ALERT_TYPE_KEYWORD\x10\x04\x12\x18\n" +
	"\x14ALERT_TYPE_FEED_DOWN\x10\x05*|\n" +
	"\vAlertStatus\x12\x1c\n" +
	"\x18ALERT_STATUS_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13ALERT_STATUS_ACTIVE\x10\x01\x12\x1a\n" +
	"\x16ALERT_STATUS_TRIGGERED\x10\x02\x12\x1a\n" +
	"\x16ALERT_STATUS_DISMISSED\x10\x03*\x8a\x01\n" +
	"\tFeedState\x12\x1a\n" +
	"\x16FEED_STATE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14FEED_STATE_CONNECTED\x10\x01\x12\x1b\n" +
	"\x17FEED_STATE_RECONNECTING\x10\x02\x12\x14\n" +
	"\x10FEED_STATE_STALE\x10\x03\x12\x14\n" +
	"\x10FEED_STATE_ERROR\x10\x04B.Z,github.com/notbbg/notbbg/server/pkg/protocolb\x06proto3"

var (
	file_notbbg_v1_types_proto_rawDescOnce sync.Once
	file_notbbg_v1_types_proto_rawDescData []byte
)

func file_notbbg_v1_types_proto_rawDescGZIP() []byte {
	file_notbbg_v1_types_proto_rawDescOnce.Do(func() {
		file_notbbg_v1_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_notbbg_v1_types_proto_rawDesc), len(file_notbbg_v1_types_proto_rawDesc)))
	})
	return file_notbbg_v1_types_proto_rawDescData
}

var file_notbbg_v1_types_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_notbbg_v1_types_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_notbbg_v1_types_proto_goTypes = []any{
	(Side)(0),                     // 0: notbbg.v1.Side
	(AlertType)(0),                // 1: notbbg.v1.AlertType
	(AlertStatus)(0),              // 2: notbbg.v1.AlertStatus
	(FeedState)(0),                // 3: notbbg.v1.FeedState
	(*OHLC)(nil),                  // 4: notbbg.v1.OHLC
	(*PriceLevel)(nil),            // 5: notbbg.v1.PriceLevel
	(*LOBSnapshot)(nil),           // 6: notbbg.v1.LOBSnapshot
	(*Trade)(nil),                 // 7: notbbg.v1.Trade
	(*NewsItem)(nil),              // 8: notbbg.v1.NewsItem
	(*Alert)(nil),                 // 9: notbbg.v1.Alert
	(*FeedStatus)(nil),            // 10: notbbg.v1.FeedStatus
	(*Subscription)(nil),          // 11: notbbg.v1.Subscription
	(*SeriesKey)(nil),             // 12: notbbg.v1.SeriesKey
	(*SeriesPoint)(nil),           // 13: notbbg.v1.SeriesPoint
	(*Update)(nil),                // 14: notbbg.v1.Update
	(*TradeAgg)(nil),              // 15: notbbg.v1.TradeAgg
	(*TradeSnap)(nil),             // 16: notbbg.v1.TradeSnap
	(*SanityRow)(nil),             // 17: notbbg.v1.SanityRow
	(*SanitySnapshot)(nil),        // 18: notbbg.v1.SanitySnapshot
	(*PluginStatus)(nil),          // 19: notbbg.v1.PluginStatus
	(*GenericRow)(nil),            // 20: notbbg.v1.GenericRow
	nil,                           // 21: notbbg.v1.Subscription.FiltersEntry
	nil,                           // 22: notbbg.v1.SeriesKey.DimsEntry
	nil,                           // 23: notbbg.v1.SanityRow.PricesEntry
	(*timestamppb.Timestamp)(nil), // 24: google.protobuf.Timestamp
	(*structpb.Struct)(nil),       // 25: google.protobuf.Struct
}
var file_notbbg_v1_types_proto_depIdxs = []int32{
	24, // 0: notbbg.v1.OHLC.timestamp:type_name -> google.protobuf.Timestamp
	24, // 1: notbbg.v1.LOBSnapshot.timestamp:type_name -> google.protobuf.Timestamp
	5,  // 2: notbbg.v1.LOBSnapshot.bids:type_name -> notbbg.v1.PriceLevel
	5,  // 3: notbbg.v1.LOBSnapshot.asks:type_name -> notbbg.v1.PriceLevel
	24, // 4: notbbg.v1.Trade.timestamp:type_name -> google.protobuf.Timestamp
	0,  // 5: notbbg.v1.Trade.side:type_name -> notbbg.v1.Side
	24, // 6: notbbg.v1.NewsItem.published_at:type_name -> google.protobuf.Timestamp
	1,  // 7: notbbg.v1.Alert.type:type_name -> notbbg.v1.AlertType
	2,  // 8: notbbg.v1.Alert.status:type_name -> notbbg.v1.AlertStatus
	24, // 9: notbbg.v1.Alert.created_at:type_name -> google.protobuf.Timestamp
	24, // 10: notbbg.v1.Alert.triggered_at:type_name -> google.protobuf.Timestamp
	24, // 11: notbbg.v1.FeedStatus.last_update:type_name -> google.protobuf.Timestamp
	3,  // 12: notbbg.v1.FeedStatus.state:type_name -> notbbg.v1.FeedState
	21, // 13: notbbg.v1.Subscription.filters:type_name -> notbbg.v1.Subscription.FiltersEntry
	22, // 14: notbbg.v1.SeriesKey.dims:type_name -> notbbg.v1.SeriesKey.DimsEntry
	12, // 15: notbbg.v1.SeriesPoint.key:type_name -> notbbg.v1.SeriesKey
	24, // 16: notbbg.v1.SeriesPoint.t:type_name -> google.protobuf.Timestamp
	4,  // 17: notbbg.v1.SeriesPoint.ohlc:type_name -> notbbg.v1.OHLC
	6,  // 18: notbbg.v1.SeriesPoint.lob:type_name -> notbbg.v1.LOBSnapshot
	7,  // 19: notbbg.v1.SeriesPoint.trade:type_name -> notbbg.v1.Trade
	24, // 20: notbbg.v1.Update.timestamp:type_name -> google.protobuf.Timestamp
	4,  // 21: notbbg.v1.Update.ohlc:type_name -> notbbg.v1.OHLC
	6,  // 22: notbbg.v1.Update.lob:type_name -> notbbg.v1.LOBSnapshot
	7,  // 23: notbbg.v1.Update.trade:type_name -> notbbg.v1.Trade
	8,  // 24: notbbg.v1.Update.news:type_name -> notbbg.v1.NewsItem
	9,  // 25: notbbg.v1.Update.alert:type_name -> notbbg.v1.Alert
	10, // 26: notbbg.v1.Update.feed_status:type_name -> notbbg.v1.FeedStatus
	24, // 27: notbbg.v1.TradeAgg.window_start:type_name -> google.protobuf.Timestamp
	24, // 28: notbbg.v1.TradeAgg.window_end:type_name -> google.protobuf.Timestamp
	24, // 29: notbbg.v1.TradeSnap.generated_at:type_name -> google.protobuf.Timestamp
	7,  // 30: notbbg.v1.TradeSnap.trades:type_name -> notbbg.v1.Trade
	24, // 31: notbbg.v1.SanityRow.updated_at:type_name -> google.protobuf.Timestamp
	23, // 32: notbbg.v1.SanityRow.prices:type_name -> notbbg.v1.SanityRow.PricesEntry
	24, // 33: notbbg.v1.SanitySnapshot.generated_at:type_name -> google.protobuf.Timestamp
	17, // 34: notbbg.v1.SanitySnapshot.rows:type_name -> notbbg.v1.SanityRow
	24, // 35: notbbg.v1.PluginStatus.last_activity:type_name -> google.protobuf.Timestamp
	24, // 36: notbbg.v1.GenericRow.observed_at:type_name -> google.protobuf.Timestamp
	25, // 37: notbbg.v1.GenericRow.payload:type_name -> google.protobuf.Struct
	38, // [38:38] is the sub-list for method output_type
	38, // [38:38] is the sub-list for method input_type
	38, // [38:38] is the sub-list for extension type_name
	38, // [38:38] is the sub-list for extension extendee
	0,  // [0:38] is the sub-list for field type_name
}

func init() { file_notbbg_v1_types_proto_init() }
func file_notbbg_v1_types_proto_init() {
	if File_notbbg_v1_types_proto != nil {
		return
	}
	file_notbbg_v1_types_proto_msgTypes[9].OneofWrappers = []any{
		(*SeriesPoint_Scalar)(nil),
		(*SeriesPoint_Ohlc)(nil),
		(*SeriesPoint_Lob)(nil),
		(*SeriesPoint_Trade)(nil),
		(*SeriesPoint_Raw)(nil),
	}
	file_notbbg_v1_types_proto_msgTypes[10].OneofWrappers = []any{
		(*Update_Ohlc)(nil),
		(*Update_Lob)(nil),
		(*Update_Trade)(nil),
		(*Update_News)(nil),
		(*Update_Alert)(nil),
		(*Update_FeedStatus)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_notbbg_v1_types_proto_rawDesc), len(file_notbbg_v1_types_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_notbbg_v1_types_proto_goTypes,
		DependencyIndexes: file_notbbg_v1_types_proto_depIdxs,
		EnumInfos:         file_notbbg_v1_types_proto_enumTypes,
		MessageInfos:      file_notbbg_v1_types_proto_msgTypes,
	}.Build()
	File_notbbg_v1_types_proto = out.File
	file_notbbg_v1_types_proto_goTypes = nil
	file_notbbg_v1_types_proto_depIdxs = nil
}
