// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: notbbg/v1/types.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Side int32

const (
	Side_SIDE_UNSPECIFIED Side = 0
	Side_SIDE_BUY         Side = 1
	Side_SIDE_SELL        Side = 2
)

// Enum value maps for Side.
var (
	Side_name = map[int32]string{
		0: "SIDE_UNSPECIFIED",
		1: "SIDE_BUY",
		2: "SIDE_SELL",
	}
	Side_value = map[string]int32{
		"SIDE_UNSPECIFIED": 0,
		"SIDE_BUY":         1,
		"SIDE_SELL":        2,
	}
)

func (x Side) Enum() *Side {
	p := new(Side)
	*p = x
	return p
}

func (x Side) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Side) Descriptor() protoreflect.EnumDescriptor {
	return file_notbbg_v1_types_proto_enumTypes[0].Descriptor()
}

func (Side) Type() protoreflect.EnumType {
	return &file_notbbg_v1_types_proto_enumTypes[0]
}

func (x Side) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Side.Descriptor instead.
func (Side) EnumDescriptor() ([]byte, []int) {
	return file_notbbg_v1_types_proto_rawDescGZIP(), []int{0}
}

type AlertType int32

const (
	AlertType_ALERT_TYPE_UNSPECIFIED  AlertType = 0
	AlertType_ALERT_TYPE_PRICE_ABOVE  AlertType = 1
	AlertType_ALERT_TYPE_PRICE_BELOW  AlertType = 2
	AlertType_ALERT_TYPE_VOLUME_SPIKE AlertType = 3
	AlertType_ALERT_TYPE_KEYWORD      AlertType = 4
	AlertType_ALERT_TYPE_FEED_DOWN    AlertType = 5
)

// Enum value maps for AlertType.
var (
	AlertType_name = map[int32]string{
		0: "ALERT_TYPE_UNSPECIFIED",
		1: "ALERT_TYPE_PRICE_ABOVE",
		2: "ALERT_TYPE_PRICE_BELOW",
		3: "ALERT_TYPE_VOLUME_SPIKE",
		4: "ALERT_TYPE_KEYWORD",
		5: "ALERT_TYPE_FEED_DOWN",
	}
	AlertType_value = map[string]int32{
		"ALERT_TYPE_UNSPECIFIED":  0,
		"ALERT_TYPE_PRICE_ABOVE":  1,
		"ALERT_TYPE_PRICE_BELOW":  2,
		"ALERT_TYPE_VOLUME_SPIKE": 3,
		"ALERT_TYPE_KEYWORD":      4,
		"ALERT_TYPE_FEED_DOWN":    5,
	}
)

func (x AlertType) Enum() *AlertType {
	p := new(AlertType)
	*p = x
	return p
}

func (x AlertType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AlertType) Descriptor() protoreflect.EnumDescriptor {
	return file_notbbg_v1_types_proto_enumTypes[1].Descriptor()
}

func (AlertType) Type() protoreflect.EnumType {
	return &file_notbbg_v1_types_proto_enumTypes[1]
}

func (x AlertType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AlertType.Descriptor instead.
func (AlertType) EnumDescriptor() ([]byte, []int) {
	return file_notbbg_v1_types_proto_rawDescGZIP(), []int{1}
}

type AlertStatus int32

const (
	AlertStatus_ALERT_STATUS_UNSPECIFIED AlertStatus = 0
	AlertStatus_ALERT_STATUS_ACTIVE      AlertStatus = 1
	AlertStatus_ALERT_STATUS_TRIGGERED   AlertStatus = 2
	AlertStatus_ALERT_STATUS_DISMISSED   AlertStatus = 3
)

// Enum value maps for AlertStatus.
var (
	AlertStatus_name = map[int32]string{
		0: "ALERT_STATUS_UNSPECIFIED",
		1: "ALERT_STATUS_ACTIVE",
		2: "ALERT_STATUS_TRIGGERED",
		3: "ALERT_STATUS_DISMISSED",
	}
	AlertStatus_value = map[string]int32{
		"ALERT_STATUS_UNSPECIFIED": 0,
		"ALERT_STATUS_ACTIVE":      1,
		"ALERT_STATUS_TRIGGERED":   2,
		"ALERT_STATUS_DISMISSED":   3,
	}
)

func (x AlertStatus) Enum() *AlertStatus {
	p := new(AlertStatus)
	*p = x
	return p
}

func (x AlertStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AlertStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_notbbg_v1_types_proto_enumTypes[2].Descriptor()
}

func (AlertStatus) Type() protoreflect.EnumType {
	return &file_notbbg_v1_types_proto_enumTypes[2]
}

func (x AlertStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AlertStatus.Descriptor instead.
func (AlertStatus) EnumDescriptor() ([]byte, []int) {
	return file_notbbg_v1_types_proto_rawDescGZIP(), []int{2}
}

type FeedState int32

const (
	FeedState_FEED_STATE_UNSPECIFIED  FeedState = 0
	FeedState_FEED_STATE_CONNECTED    FeedState = 1
	FeedState_FEED_STATE_RECONNECTING FeedState = 2
	FeedState_FEED_STATE_STALE        FeedState = 3
	FeedState_FEED_STATE_ERROR        FeedState = 4
)

// Enum value maps for FeedState.
var (
	FeedState_name = map[int32]string{
		0: "FEED_STATE_UNSPECIFIED",
		1: "FEED_STATE_CONNECTED",
		2: "FEED_STATE_RECONNECTING",
		3: "FEED_STATE_STALE",
		4: "FEED_STATE_ERROR",
	}
	FeedState_value = map[string]int32{
		"FEED_STATE_UNSPECIFIED":  0,
		"FEED_STATE_CONNECTED":    1,
		"FEED_STATE_RECONNECTING": 2,
		"FEED_STATE_STALE":        3,
		"FEED_STATE_ERROR":        4,
	}
)

func (x FeedState) Enum() *FeedState {
	p := new(FeedState)
	*p = x
	return p
}

func (x FeedState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FeedState) Descriptor() protoreflect.EnumDescriptor {
	return file_notbbg_v1_types_proto_enumTypes[3].Descriptor()
}

func (FeedState) Type() protoreflect.EnumType {
	return &file_notbbg_v1_types_proto_enumTypes[3]
}

func (x FeedState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FeedState.Descriptor instead.
func (FeedState) EnumDescriptor() ([]byte, []int) {
	return file_notbbg_v1_types_proto_rawDescGZIP(), []int{3}
}

// Canonical OHLC candlestick data.
type OHLC struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Instrument    string                 `protobuf:"bytes,1,opt,name=instrument,proto3" json:"instrument,omitempty"` // e.g. "BTCUSD"
	Exchange      string                 `protobuf:"bytes,2,opt,name=exchange,proto3" json:"exchange,omitempty"`     // e.g. "binance"
	Timeframe     string                 `protobuf:"bytes,3,opt,name=timeframe,proto3" json:"timeframe,omitempty"`   // e.g. "1m", "5m", "1h", "1d"
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Open          float64                `protobuf:"fixed64,5,opt,name=open,proto3" json:"open,omitempty"`
	High          float64                `protobuf:"fixed64,6,opt,name=high,proto3" json:"high,omitempty"`
	Low           float64                `protobuf:"fixed64,7,opt,name=low,proto3" json:"low,omitempty"`
	Close         float64                `protobuf:"fixed64,8,opt,name=close,proto3" json:"close,omitempty"`
	Volume        float64                `protobuf:"fixed64,9,opt,name=volume,proto3" json:"volume,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OHLC) Reset() {
	*x = OHLC{}
	mi := &file_notbbg_v1_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OHLC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OHLC) ProtoMessage() {}

func (x *OHLC) ProtoReflect() protoreflect.Message {
	mi := &file_notbbg_v1_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OHLC.ProtoReflect.Descriptor instead.
func (*OHLC) Descriptor() ([]byte, []int) {
	return file_notbbg_v1_types_proto_rawDescGZIP(), []int{0}
}

func (x *OHLC) GetInstrument() string {
	if x != nil {
		return x.Instrument
	}
	return ""
}

func (x *OHLC) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

func (x *OHLC) GetTimeframe() string {
	if x != nil {
		return x.Timeframe
	}
	return ""
}

func (x *OHLC) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *OHLC) GetOpen() float64 {
	if x != nil {
		return x.Open
	}
	return 0
}

func (x *OHLC) GetHigh() float64 {
	if x != nil {
		return x.High
	}
	return 0
}

func (x *OHLC) GetLow() float64 {
	if x != nil {
		return x.Low
	}
	return 0
}

func (x *OHLC) GetClose() float64 {
	if x != nil {
		return x.Close
	}
	return 0
}

func (x *OHLC) GetVolume() float64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

// Single price level in an order book.
type PriceLevel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Price         float64                `protobuf:"fixed64,1,opt,name=price,proto3" json:"price,omitempty"`
	Quantity      float64                `protobuf:"fixed64,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PriceLevel) Reset() {
	*x = PriceLevel{}
	mi := &file_notbbg_v1_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PriceLevel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriceLevel) ProtoMessage() {}

func (x *PriceLevel) ProtoReflect() protoreflect.Message {
	mi := &file_notbbg_v1_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriceLevel.ProtoReflect.Descriptor instead.
func (*PriceLevel) Descriptor() ([]byte, []int) {
	return file_notbbg_v1_types_proto_rawDescGZIP(), []int{1}
}

func (x *PriceLevel) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *PriceLevel) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

// Snapshot of a limit order book.
type LOBSnapshot struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Instrument     string                 `protobuf:"bytes,1,opt,name=instrument,proto3" json:"instrument,omitempty"`
	Exchange       string                 `protobuf:"bytes,2,opt,name=exchange,proto3" json:"exchange,omitempty"`
	Timestamp      *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	SequenceNumber uint64                 `protobuf:"varint,4,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	Bids           []*PriceLevel          `protobuf:"bytes,5,rep,name=bids,proto3" json:"bids,omitempty"`
	Asks           []*PriceLevel          `protobuf:"bytes,6,rep,name=asks,proto3" json:"asks,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LOBSnapshot) Reset() {
	*x = LOBSnapshot{}
	mi := &file_notbbg_v1_types_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LOBSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LOBSnapshot) ProtoMessage() {}

func (x *LOBSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_notbbg_v1_types_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LOBSnapshot.ProtoReflect.Descriptor instead.
func (*LOBSnapshot) Descriptor() ([]byte, []int) {
	return file_notbbg_v1_types_proto_rawDescGZIP(), []int{2}
}

func (x *LOBSnapshot) GetInstrument() string {
	if x != nil {
		return x.Instrument
	}
	return ""
}

func (x *LOBSnapshot) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

func (x *LOBSnapshot) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *LOBSnapshot) GetSequenceNumber() uint64 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

func (x *LOBSnapshot) GetBids() []*PriceLevel {
	if x != nil {
		return x.Bids
	}
	return nil
}

func (x *LOBSnapshot) GetAsks() []*PriceLevel {
	if x != nil {
		return x.Asks
	}
	return nil
}

// A single executed trade.
type Trade struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Instrument    string                 `protobuf:"bytes,1,opt,name=instrument,proto3" json:"instrument,omitempty"`
	Exchange      string                 `protobuf:"bytes,2,opt,name=exchange,proto3" json:"exchange,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Price         float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	Quantity      float64                `protobuf:"fixed64,5,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Side          Side                   `protobuf:"varint,6,opt,name=side,proto3,enum=notbbg.v1.Side" json:"side,omitempty"`
	TradeId       string                 `protobuf:"bytes,7,opt,name=trade_id,json=tradeId,proto3" json:"trade_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Trade) Reset() {
	*x = Trade{}
	mi := &file_notbbg_v1_types_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Trade) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Trade) ProtoMessage() {}

func (x *Trade) ProtoReflect() protoreflect.Message {
	mi := &file_notbbg_v1_types_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Trade.ProtoReflect.Descriptor instead.
func (*Trade) Descriptor() ([]byte, []int) {
	return file_notbbg_v1_types_proto_rawDescGZIP(), []int{3}
}

func (x *Trade) GetInstrument() string {
	if x != nil {
		return x.Instrument
	}
	return ""
}

func (x *Trade) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

func (x *Trade) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Trade) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Trade) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *Trade) GetSide() Side {
	if x != nil {
		return x.Side
	}
	return Side_SIDE_UNSPECIFIED
}

func (x *Trade) GetTradeId() string {
	if x != nil {
		return x.TradeId
	}
	return ""
}

// A news item from RSS, GDELT, or other sources.
type NewsItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Body          string                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	Source        string                 `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"` // e.g. "reuters", "coindesk"
	Url           string                 `protobuf:"bytes,5,opt,name=url,proto3" json:"url,omitempty"`
	PublishedAt   *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=published_at,json=publishedAt,proto3" json:"published_at,omitempty"`
	Tickers       []string               `protobuf:"bytes,7,rep,name=tickers,proto3" json:"tickers,omitempty"` // related tickers
	Keywords      []string               `protobuf:"bytes,8,rep,name=keywords,proto3" json:"keywords,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewsItem) Reset() {
	*x = NewsItem{}
	mi := &file_notbbg_v1_types_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewsItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewsItem) ProtoMessage() {}

func (x *NewsItem) ProtoReflect() protoreflect.Message {
	mi := &file_notbbg_v1_types_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewsItem.ProtoReflect.Descriptor instead.
func (*NewsItem) Descriptor() ([]byte, []int) {
	return file_notbbg_v1_types_proto_rawDescGZIP(), []int{4}
}

func (x *NewsItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NewsItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *NewsItem) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *NewsItem) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *NewsItem) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *NewsItem) GetPublishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PublishedAt
	}
	return nil
}

func (x *NewsItem) GetTickers() []string {
	if x != nil {
		return x.Tickers
	}
	return nil
}

func (x *NewsItem) GetKeywords() []string {
	if x != nil {
		return x.Keywords
	}
	return nil
}

// An alert definition or triggered alert.
type Alert struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          AlertType              `protobuf:"varint,2,opt,name=type,proto3,enum=notbbg.v1.AlertType" json:"type,omitempty"`
	Instrument    string                 `protobuf:"bytes,3,opt,name=instrument,proto3" json:"instrument,omitempty"` // empty for keyword/feed alerts
	Condition     string                 `protobuf:"bytes,4,opt,name=condition,proto3" json:"condition,omitempty"`   // human-readable condition, e.g. "> 100000"
	Threshold     float64                `protobuf:"fixed64,5,opt,name=threshold,proto3" json:"threshold,omitempty"`
	Status        AlertStatus            `protobuf:"varint,6,opt,name=status,proto3,enum=notbbg.v1.AlertStatus" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	TriggeredAt   *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=triggered_at,json=triggeredAt,proto3" json:"triggered_at,omitempty"`
	Payload       string                 `protobuf:"bytes,9,opt,name=payload,proto3" json:"payload,omitempty"` // additional context when triggered
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Alert) Reset() {
	*x = Alert{}
	mi := &file_notbbg_v1_types_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Alert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Alert) ProtoMessage() {}

func (x *Alert) ProtoReflect() protoreflect.Message {
	mi := &file_notbbg_v1_types_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Alert.ProtoReflect.Descriptor instead.
func (*Alert) Descriptor() ([]byte, []int) {
	return file_notbbg_v1_types_proto_rawDescGZIP(), []int{5}
}

func (x *Alert) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Alert) GetType() AlertType {
	if x != nil {
		return x.Type
	}
	return AlertType_ALERT_TYPE_UNSPECIFIED
}

func (x *Alert) GetInstrument() string {
	if x != nil {
		return x.Instrument
	}
	return ""
}

func (x *Alert) GetCondition() string {
	if x != nil {
		return x.Condition
	}
	return ""
}

func (x *Alert) GetThreshold() float64 {
	if x != nil {
		return x.Threshold
	}
	return 0
}

func (x *Alert) GetStatus() AlertStatus {
	if x != nil {
		return x.Status
	}
	return AlertStatus_ALERT_STATUS_UNSPECIFIED
}

func (x *Alert) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Alert) GetTriggeredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.TriggeredAt
	}
	return nil
}

func (x *Alert) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

// Health status of a data feed.
type FeedStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceName    string                 `protobuf:"bytes,1,opt,name=source_name,json=sourceName,proto3" json:"source_name,omitempty"`
	LastUpdate    *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=last_update,json=lastUpdate,proto3" json:"last_update,omitempty"`
	LatencyP50Ms  float64                `protobuf:"fixed64,3,opt,name=latency_p50_ms,json=latencyP50Ms,proto3" json:"latency_p50_ms,omitempty"`
	LatencyP95Ms  float64                `protobuf:"fixed64,4,opt,name=latency_p95_ms,json=latencyP95Ms,proto3" json:"latency_p95_ms,omitempty"`
	LatencyP99Ms  float64                `protobuf:"fixed64,5,opt,name=latency_p99_ms,json=latencyP99Ms,proto3" json:"latency_p99_ms,omitempty"`
	ErrorCount    uint64                 `protobuf:"varint,6,opt,name=error_count,json=errorCount,proto3" json:"error_count,omitempty"`
	BytesReceived uint64                 `protobuf:"varint,7,opt,name=bytes_received,json=bytesReceived,proto3" json:"bytes_received,omitempty"`
	State         FeedState              `protobuf:"varint,8,opt,name=state,proto3,enum=notbbg.v1.FeedState" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeedStatus) Reset() {
	*x = FeedStatus{}
	mi := &file_notbbg_v1_types_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeedStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedStatus) ProtoMessage() {}

func (x *FeedStatus) ProtoReflect() protoreflect.Message {
	mi := &file_notbbg_v1_types_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedStatus.ProtoReflect.Descriptor instead.
func (*FeedStatus) Descriptor() ([]byte, []int) {
	return file_notbbg_v1_types_proto_rawDescGZIP(), []int{6}
}

func (x *FeedStatus) GetSourceName() string {
	if x != nil {
		return x.SourceName
	}
	return ""
}

func (x *FeedStatus) GetLastUpdate() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUpdate
	}
	return nil
}

func (x *FeedStatus) GetLatencyP50Ms() float64 {
	if x != nil {
		return x.LatencyP50Ms
	}
	return 0
}

func (x *FeedStatus) GetLatencyP95Ms() float64 {
	if x != nil {
		return x.LatencyP95Ms
	}
	return 0
}

func (x *FeedStatus) GetLatencyP99Ms() float64 {
	if x != nil {
		return x.LatencyP99Ms
	}
	return 0
}

func (x *FeedStatus) GetErrorCount() uint64 {
	if x != nil {
		return x.ErrorCount
	}
	return 0
}

func (x *FeedStatus) GetBytesReceived() uint64 {
	if x != nil {
		return x.BytesReceived
	}
	return 0
}

func (x *FeedStatus) GetState() FeedState {
	if x != nil {
		return x.State
	}
	return FeedState_FEED_STATE_UNSPECIFIED
}

// A topic subscription request from a client.
type Subscription struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"` // glob pattern, e.g. "ohlc.binance.*"
	Filters       map[string]string      `protobuf:"bytes,2,rep,name=filters,proto3" json:"filters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Subscription) Reset() {
	*x = Subscription{}
	mi := &file_notbbg_v1_types_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subscription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subscription) ProtoMessage() {}

func (x *Subscription) ProtoReflect() protoreflect.Message {
	mi := &file_notbbg_v1_types_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subscription.ProtoReflect.Descriptor instead.
func (*Subscription) Descriptor() ([]byte, []int) {
	return file_notbbg_v1_types_proto_rawDescGZIP(), []int{7}
}

func (x *Subscription) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *Subscription) GetFilters() map[string]string {
	if x != nil {
		return x.Filters
	}
	return nil
}

// Wrapper for any message sent over the bus or wire.
type Update struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Topic     string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Update_Ohlc
	//	*Update_Lob
	//	*Update_Trade
	//	*Update_News
	//	*Update_Alert
	//	*Update_FeedStatus
	Payload       isUpdate_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Update) Reset() {
	*x = Update{}
	mi := &file_notbbg_v1_types_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Update) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Update) ProtoMessage() {}

func (x *Update) ProtoReflect() protoreflect.Message {
	mi := &file_notbbg_v1_types_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Update.ProtoReflect.Descriptor instead.
func (*Update) Descriptor() ([]byte, []int) {
	return file_notbbg_v1_types_proto_rawDescGZIP(), []int{8}
}

func (x *Update) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *Update) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Update) GetPayload() isUpdate_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Update) GetOhlc() *OHLC {
	if x != nil {
		if x, ok := x.Payload.(*Update_Ohlc); ok {
			return x.Ohlc
		}
	}
	return nil
}

func (x *Update) GetLob() *LOBSnapshot {
	if x != nil {
		if x, ok := x.Payload.(*Update_Lob); ok {
			return x.Lob
		}
	}
	return nil
}

func (x *Update) GetTrade() *Trade {
	if x != nil {
		if x, ok := x.Payload.(*Update_Trade); ok {
			return x.Trade
		}
	}
	return nil
}

func (x *Update) GetNews() *NewsItem {
	if x != nil {
		if x, ok := x.Payload.(*Update_News); ok {
			return x.News
		}
	}
	return nil
}

func (x *Update) GetAlert() *Alert {
	if x != nil {
		if x, ok := x.Payload.(*Update_Alert); ok {
			return x.Alert
		}
	}
	return nil
}

func (x *Update) GetFeedStatus() *FeedStatus {
	if x != nil {
		if x, ok := x.Payload.(*Update_FeedStatus); ok {
			return x.FeedStatus
		}
	}
	return nil
}

type isUpdate_Payload interface {
	isUpdate_Payload()
}

type Update_Ohlc struct {
	Ohlc *OHLC `protobuf:"bytes,10,opt,name=ohlc,proto3,oneof"`
}

type Update_Lob struct {
	Lob *LOBSnapshot `protobuf:"bytes,11,opt,name=lob,proto3,oneof"`
}

type Update_Trade struct {
	Trade *Trade `protobuf:"bytes,12,opt,name=trade,proto3,oneof"`
}

type Update_News struct {
	News *NewsItem `protobuf:"bytes,13,opt,name=news,proto3,oneof"`
}

type Update_Alert struct {
	Alert *Alert `protobuf:"bytes,14,opt,name=alert,proto3,oneof"`
}

type Update_FeedStatus struct {
	FeedStatus *FeedStatus `protobuf:"bytes,15,opt,name=feed_status,json=feedStatus,proto3,oneof"`
}

func (*Update_Ohlc) isUpdate_Payload() {}

func (*Update_Lob) isUpdate_Payload() {}

func (*Update_Trade) isUpdate_Payload() {}

func (*Update_News) isUpdate_Payload() {}

func (*Update_Alert) isUpdate_Payload() {}

func (*Update_FeedStatus) isUpdate_Payload() {}

var File_notbbg_v1_types_proto protoreflect.FileDescriptor

const file_notbbg_v1_types_proto_rawDesc = "" +
	"\n" +
	"\x15notbbg/v1/types.proto\x12\tnotbbg.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x82\x02\n" +
	"\x04OHLC\x12\x1e\n" +
	"\n" +
	"instrument\x18\x01 \x01(\tR\n" +
	"instrument\x12\x1a\n" +
	"\bexchange\x18\x02 \x01(\tR\bexchange\x12\x1c\n" +
	"\ttimeframe\x18\x03 \x01(\tR\ttimeframe\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x12\n" +
	"\x04open\x18\x05 \x01(\x01R\x04open\x12\x12\n" +
	"\x04high\x18\x06 \x01(\x01R\x04high\x12\x10\n" +
	"\x03low\x18\a \x01(\x01R\x03low\x12\x14\n" +
	"\x05close\x18\b \x01(\x01R\x05close\x12\x16\n" +
	"\x06volume\x18\t \x01(\x01R\x06volume\">\n" +
	"\n" +
	"PriceLevel\x12\x14\n" +
	"\x05price\x18\x01 \x01(\x01R\x05price\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x01R\bquantity\"\x82\x02\n" +
	"\vLOBSnapshot\x12\x1e\n" +
	"\n" +
	"instrument\x18\x01 \x01(\tR\n" +
	"instrument\x12\x1a\n" +
	"\bexchange\x18\x02 \x01(\tR\bexchange\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12'\n" +
	"\x0fsequence_number\x18\x04 \x01(\x04R\x0esequenceNumber\x12)\n" +
	"\x04bids\x18\x05 \x03(\v2\x15.notbbg.v1.PriceLevelR\x04bids\x12)\n" +
	"\x04asks\x18\x06 \x03(\v2\x15.notbbg.v1.PriceLevelR\x04asks\"\xef\x01\n" +
	"\x05Trade\x12\x1e\n" +
	"\n" +
	"instrument\x18\x01 \x01(\tR\n" +
	"instrument\x12\x1a\n" +
	"\bexchange\x18\x02 \x01(\tR\bexchange\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\x12\x1a\n" +
	"\bquantity\x18\x05 \x01(\x01R\bquantity\x12#\n" +
	"\x04side\x18\x06 \x01(\x0e2\x0f.notbbg.v1.SideR\x04side\x12\x19\n" +
	"\btrade_id\x18\a \x01(\tR\atradeId\"\xe3\x01\n" +
	"\bNewsItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04body\x18\x03 \x01(\tR\x04body\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\x12\x10\n" +
	"\x03url\x18\x05 \x01(\tR\x03url\x12=\n" +
	"\fpublished_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\vpublishedAt\x12\x18\n" +
	"\atickers\x18\a \x03(\tR\atickers\x12\x1a\n" +
	"\bkeywords\x18\b \x03(\tR\bkeywords\"\xe1\x02\n" +
	"\x05Alert\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12(\n" +
	"\x04type\x18\x02 \x01(\x0e2\x14.notbbg.v1.AlertTypeR\x04type\x12\x1e\n" +
	"\n" +
	"instrument\x18\x03 \x01(\tR\n" +
	"instrument\x12\x1c\n" +
	"\tcondition\x18\x04 \x01(\tR\tcondition\x12\x1c\n" +
	"\tthreshold\x18\x05 \x01(\x01R\tthreshold\x12.\n" +
	"\x06status\x18\x06 \x01(\x0e2\x16.notbbg.v1.AlertStatusR\x06status\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12=\n" +
	"\ftriggered_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\vtriggeredAt\x12\x18\n" +
	"\apayload\x18\t \x01(\tR\apayload\"\xd0\x02\n" +
	"\n" +
	"FeedStatus\x12\x1f\n" +
	"\vsource_name\x18\x01 \x01(\tR\n" +
	"sourceName\x12;\n" +
	"\vlast_update\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastUpdate\x12$\n" +
	"\x0elatency_p50_ms\x18\x03 \x01(\x01R\flatencyP50Ms\x12$\n" +
	"\x0elatency_p95_ms\x18\x04 \x01(\x01R\flatencyP95Ms\x12$\n" +
	"\x0elatency_p99_ms\x18\x05 \x01(\x01R\flatencyP99Ms\x12\x1f\n" +
	"\verror_count\x18\x06 \x01(\x04R\n" +
	"errorCount\x12%\n" +
	"\x0ebytes_received\x18\a \x01(\x04R\rbytesReceived\x12*\n" +
	"\x05state\x18\b \x01(\x0e2\x14.notbbg.v1.FeedStateR\x05state\"\xa0\x01\n" +
	"\fSubscription\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12>\n" +
	"\afilters\x18\x02 \x03(\v2$.notbbg.v1.Subscription.FiltersEntryR\afilters\x1a:\n" +
	"\fFiltersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xef\x02\n" +
	"\x06Update\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12%\n" +
	"\x04ohlc\x18\n" +
	" \x01(\v2\x0f.notbbg.v1.OHLCH\x00R\x04ohlc\x12*\n" +
	"\x03lob\x18\v \x01(\v2\x16.notbbg.v1.LOBSnapshotH\x00R\x03lob\x12(\n" +
	"\x05trade\x18\f \x01(\v2\x10.notbbg.v1.TradeH\x00R\x05trade\x12)\n" +
	"\x04news\x18\r \x01(\v2\x13.notbbg.v1.NewsItemH\x00R\x04news\x12(\n" +
	"\x05alert\x18\x0e \x01(\v2\x10.notbbg.v1.AlertH\x00R\x05alert\x128\n" +
	"\vfeed_status\x18\x0f \x01(\v2\x15.notbbg.v1.FeedStatusH\x00R\n" +
	"feedStatusB\t\n" +
	"\apayload*9\n" +
	"\x04Side\x12\x14\n" +
	"\x10SIDE_UNSPECIFIED\x10\x00\x12\f\n" +
	"\bSIDE_BUY\x10\x01\x12\r\n" +
	"\tSIDE_SELL\x10\x02*\xae\x01\n" +
	"\tAlertType\x12\x1a\n" +
	"\x16ALERT_TYPE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16ALERT_TYPE_PRICE_ABOVE\x10\x01\x12\x1a\n" +
	"\x16ALERT_TYPE_PRICE_BELOW\x10\x02\x12\x1b\n" +
	"\x17ALERT_TYPE_VOLUME_SPIKE\x10\x03\x12\x16\n" +
	"\x12ALERT_TYPE_KEYWORD\x10\x04\x12\x18\n" +
	"\x14ALERT_TYPE_FEED_DOWN\x10\x05*|\n" +
	"\vAlertStatus\x12\x1c\n" +
	"\x18ALERT_STATUS_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13ALERT_STATUS_ACTIVE\x10\x01\x12\x1a\n" +
	"\x16ALERT_STATUS_TRIGGERED\x10\x02\x12\x1a\n" +
	"\x16ALERT_STATUS_DISMISSED\x10\x03*\x8a\x01\n" +
	"\tFeedState\x12\x1a\n" +
	"\x16FEED_STATE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14FEED_STATE_CONNECTED\x10\x01\x12\x1b\n" +
	"\x17FEED_STATE_RECONNECTING\x10\x02\x12\x14\n" +
	"\x10FEED_STATE_STALE\x10\x03\x12\x14\n" +
	"\x10FEED_STATE_ERROR\x10\x04B.Z,github.com/notbbg/notbbg/server/pkg/protocolb\x06proto3"

var (
	file_notbbg_v1_types_proto_rawDescOnce sync.Once
	file_notbbg_v1_types_proto_rawDescData []byte
)

func file_notbbg_v1_types_proto_rawDescGZIP() []byte {
	file_notbbg_v1_types_proto_rawDescOnce.Do(func() {
		file_notbbg_v1_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_notbbg_v1_types_proto_rawDesc), len(file_notbbg_v1_types_proto_rawDesc)))
	})
	return file_notbbg_v1_types_proto_rawDescData
}

var file_notbbg_v1_types_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_notbbg_v1_types_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_notbbg_v1_types_proto_goTypes = []any{
	(Side)(0),                     // 0: notbbg.v1.Side
	(AlertType)(0),                // 1: notbbg.v1.AlertType
	(AlertStatus)(0),              // 2: notbbg.v1.AlertStatus
	(FeedState)(0),                // 3: notbbg.v1.FeedState
	(*OHLC)(nil),                  // 4: notbbg.v1.OHLC
	(*PriceLevel)(nil),            // 5: notbbg.v1.PriceLevel
	(*LOBSnapshot)(nil),           // 6: notbbg.v1.LOBSnapshot
	(*Trade)(nil),                 // 7: notbbg.v1.Trade
	(*NewsItem)(nil),              // 8: notbbg.v1.NewsItem
	(*Alert)(nil),                 // 9: notbbg.v1.Alert
	(*FeedStatus)(nil),            // 10: notbbg.v1.FeedStatus
	(*Subscription)(nil),          // 11: notbbg.v1.Subscription
	(*Update)(nil),                // 12: notbbg.v1.Update
	nil,                           // 13: notbbg.v1.Subscription.FiltersEntry
	(*timestamppb.Timestamp)(nil), // 14: google.protobuf.Timestamp
}
var file_notbbg_v1_types_proto_depIdxs = []int32{
	14, // 0: notbbg.v1.OHLC.timestamp:type_name -> google.protobuf.Timestamp
	14, // 1: notbbg.v1.LOBSnapshot.timestamp:type_name -> google.protobuf.Timestamp
	5,  // 2: notbbg.v1.LOBSnapshot.bids:type_name -> notbbg.v1.PriceLevel
	5,  // 3: notbbg.v1.LOBSnapshot.asks:type_name -> notbbg.v1.PriceLevel
	14, // 4: notbbg.v1.Trade.timestamp:type_name -> google.protobuf.Timestamp
	0,  // 5: notbbg.v1.Trade.side:type_name -> notbbg.v1.Side
	14, // 6: notbbg.v1.NewsItem.published_at:type_name -> google.protobuf.Timestamp
	1,  // 7: notbbg.v1.Alert.type:type_name -> notbbg.v1.AlertType
	2,  // 8: notbbg.v1.Alert.status:type_name -> notbbg.v1.AlertStatus
	14, // 9: notbbg.v1.Alert.created_at:type_name -> google.protobuf.Timestamp
	14, // 10: notbbg.v1.Alert.triggered_at:type_name -> google.protobuf.Timestamp
	14, // 11: notbbg.v1.FeedStatus.last_update:type_name -> google.protobuf.Timestamp
	3,  // 12: notbbg.v1.FeedStatus.state:type_name -> notbbg.v1.FeedState
	13, // 13: notbbg.v1.Subscription.filters:type_name -> notbbg.v1.Subscription.FiltersEntry
	14, // 14: notbbg.v1.Update.timestamp:type_name -> google.protobuf.Timestamp
	4,  // 15: notbbg.v1.Update.ohlc:type_name -> notbbg.v1.OHLC
	6,  // 16: notbbg.v1.Update.lob:type_name -> notbbg.v1.LOBSnapshot
	7,  // 17: notbbg.v1.Update.trade:type_name -> notbbg.v1.Trade
	8,  // 18: notbbg.v1.Update.news:type_name -> notbbg.v1.NewsItem
	9,  // 19: notbbg.v1.Update.alert:type_name -> notbbg.v1.Alert
	10, // 20: notbbg.v1.Update.feed_status:type_name -> notbbg.v1.FeedStatus
	21, // [21:21] is the sub-list for method output_type
	21, // [21:21] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_notbbg_v1_types_proto_init() }
func file_notbbg_v1_types_proto_init() {
	if File_notbbg_v1_types_proto != nil {
		return
	}
	file_notbbg_v1_types_proto_msgTypes[8].OneofWrappers = []any{
		(*Update_Ohlc)(nil),
		(*Update_Lob)(nil),
		(*Update_Trade)(nil),
		(*Update_News)(nil),
		(*Update_Alert)(nil),
		(*Update_FeedStatus)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_notbbg_v1_types_proto_rawDesc), len(file_notbbg_v1_types_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_notbbg_v1_types_proto_goTypes,
		DependencyIndexes: file_notbbg_v1_types_proto_depIdxs,
		EnumInfos:         file_notbbg_v1_types_proto_enumTypes,
		MessageInfos:      file_notbbg_v1_types_proto_msgTypes,
	}.Build()
	File_notbbg_v1_types_proto = out.File
	file_notbbg_v1_types_proto_goTypes = nil
	file_notbbg_v1_types_proto_depIdxs = nil
}
